package org.springframework.nativex;

/**
 * Thrown when a class generated by the AOT plugin is not found.
 *
 * @author Sebastien Deleuze
 */
public class GeneratedClassNotFoundException extends RuntimeException {

	private final String className;

	public GeneratedClassNotFoundException(String className) {
		super(String.format(
				"The ApplicationContext could not start as '%s' that is generated by the Spring AOT plugin could not be found.", className));
		this.className = className;
	}

	public String getClassName() {
		return this.className;
	}
}
