CREATE TABLE PERSON  (
     FIRST_NAME VARCHAR(20) NOT NULL,
     LAST_NAME VARCHAR(20) NOT NULL,
     ADDRESS VARCHAR(255) NOT NULL,
     CITY VARCHAR(100) NOT NULL,
     STATE VARCHAR(2) NOT NULL,
     ZIP VARCHAR(5) NOT NULL
) ENGINE=InnoDB;
