:version: 0.9.0
:repository: release
:spring-boot-version: 2.4.3
:graalvm-version: 20.1.0
:graalvm-dev-version: 20.1.0
:spring-boot-dev-version: 2.4.3
:documentation-url: https://docs.spring.io/spring-native/docs/current/reference/htmlsingle

image:https://ci.spring.io/api/v1/teams/spring-native/pipelines/spring-native/badge["Build Status", link="https://ci.spring.io/teams/spring-native/pipelines/spring-native"] image:https://img.shields.io/badge/{version}-documentation-blue.svg["{version} documentation", link="{documentation-url}"]

Spring Native provides an incubating support for compiling Spring applications to native executables using https://www.graalvm.org[GraalVM] 
https://www.graalvm.org/reference-manual/native-image/[native-image] compiler, in order to provide a native deployment
option typically designed to be packaged in lightweight containers. In practice, the target is to support your Spring Boot application
, almost unmodified, on this new platform.

It is mainly composed of:

- `spring-native`: this module contains the runtime dependency required for running Spring native like the substitutions.
- `spring-native-configuration`: this module contains configuration hints for Spring classes, including various Spring Boot auto-configurations.
- `spring-native-docs`: contains the asciidoc documentation sources.
- `spring-native-tools`: tools used for reviewing image building configuration and output.
- `spring-aot`: this module contains the AOT transformation infrastructure common to Maven and Gradle plugins.
- `spring-aot-gradle-plugin`: this module contains the Gradle plugin that invokes AOT transformations.
- `spring-aot-maven-plugin`: this module contains the Maven plugin that invokes AOT transformations.
- `samples`: contains various samples that demonstrate the feature usage and are used as integration tests.

== Quick start

For detailed information and walkthroughs of applying the techniques to your project, please see the {documentation-url}[documentation].

=== Play with the samples

NOTE: You need to install the GraalVM `native-image` compiler, check {documentation-url}/#getting-started-native-image[the documentation] for more details.

- Download and extract https://github.com/spring-projects-experimental/spring-native/archive/{version}.zip[sources from the latest release].
- Go into the samples folder and pick one (e.g. `cd samples/commandlinerunner`)
- Run `./build.sh` which will run a maven build, then a native image compile, then test the result.

`build.sh` runs the `compile.sh` script and in that compile script you can see the invocation of the `native-image` command. The other samples follow a similar model. For more details on the samples see the {documentation-url}/index.html#samples[samples documentation].

== Contributing

This project is in the `spring-projects-experimental` org indicating it is not as mature as other Spring projects. Contributions are welcome (please refer to the {documentation-url}/index.html#how-to-contribute[how to contribute] section).
However, please recognize we aren't at the polishing javadoc stage and whilst pre 1.0 there may be heavy evolution of APIs.

=== Baseline

The development version on `master` is currently based on GraalVM {graalvm-dev-version} and Spring Boot {spring-boot-dev-version}.
Mac, Linux and Windows are supported.

== License

https://www.apache.org/licenses/LICENSE-2.0[Apache License v2.0]
