[[feature]]
=== Using the feature

This section walks through how to try building a native image for a Spring Boot project.
This is a practical guide, so we perform this for real on the https://spring.io/guides/gs/rest-service/[REST service getting started guide].

==== Download and install GraalVM

From GraalVM builds:

- Install GraalVM {graal-version} Java 8 distribution from https://github.com/graalvm/graalvm-ce-builds/releases[here]
- Set `JAVA_HOME` and `PATH` appropriately for that GraalVM version.
- Run `gu install native-image` to bring in the native-image extensions to the JDK.

Or you can use https://sdkman.io/[SDKMAN] to easily switch between GraalVM versions:

- https://sdkman.io/install[Install SDKMAN]
- Install GraalVM with `sdk install java {graal-version}.r8-grl`
- Run `gu install native-image` to bring in the native-image extensions to the JDK.

==== Set up the sample project

Like the instructions for using the feature, here we use the getting started REST service guide.
This is the sample project we trace with the agent and then build into a native image.
The following commands install the REST service guide:

====
[source,bash]
----
git clone https://github.com/spring-guides/gs-rest-service
cd gs-rest-service/complete
----
====

You may already be ready to go with your own project.

===== Update the `pom.xml` file

IMPORTANT: Ensure that the project uses a supported version of Spring Boot.

Upgrade the project to Spring Boot {boot-version}:

====
[source,xml,subs="attributes,verbatim"]
----
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>{boot-version}</version>
    <relativePath/> <!-- lookup parent from repository -->
</parent>
----
====

And add the following repositories to the `pom.xml` file if needed:

====
[source,xml,subs="attributes,verbatim"]
----
<pluginRepositories>
    <!-- ... -->
    <pluginRepository>
        <id>spring-{boot-repository}</id>
        <name>Spring {boot-repository}</name>
        <url>https://repo.spring.io/{boot-repository}</url>
    </pluginRepository>
</pluginRepositories>
----
====

And

====
[source,xml,subs="attributes,verbatim"]
----
<repositories>
    <!-- ... -->
    <repository>
        <id>spring-{boot-repository}</id>
        <name>Spring {boot-repository}</name>
        <url>https://repo.spring.io/{boot-repository}</url>
    </repository>
</repositories>
----
====

===== Add the Maven plugin

GraalVM provides a https://www.graalvm.org/docs/reference-manual/native-image/#integration-with-maven[Maven plugin].
Paste the following XML into the `pom.xml` file (we use it later to invoke the native image build):

====
[source,xml,subs="attributes,verbatim"]
----
<profiles>
  <profile>
    <id>graal</id>
    <build>
      <plugins>
        <plugin>
          <groupId>org.graalvm.nativeimage</groupId>
          <artifactId>native-image-maven-plugin</artifactId>
          <version>{graal-version}</version>
          <configuration>
            <buildArgs>-Dspring.graal.remove-unused-autoconfig=true --no-fallback -H:+ReportExceptionStackTraces --no-server</buildArgs>
          </configuration>
          <executions>
            <execution>
              <goals>
                <goal>native-image</goal>
              </goals>
              <phase>package</phase>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-maven-plugin</artifactId>
        </plugin>
      </plugins>
    </build>
  </profile>
</profiles>
----
====

The important part is the `<buildArgs>..</buildArgs>` block, which shows the options we pass to the `native-image` operation and the `spring-graal-native` feature.
Those prefixed `-D` are aimed at the feature.

NOTE: Notice the `--no-server` option.
Like a Gradle daemon, the server here is supposed to help accelerate subsequent builds. Unfortunately, there is an https://github.com/oracle/graal/issues/1952[issue] where the server causes different results to come out of the compilation.
In particular, we have seen logging disappear if the server is used to aid compilation.
Hence, using the server to aid compilation is turned off here.

The `-Dspring.graal.remove-unused-autoconfig=true` is an option we can use to evaluate some of the Spring Boot conditions at image-build time.
One example of such an option is `@ConditionalOnClass`.
Because `native-image` runs at a point when the full classpath is known, we can know for certain if a class is present.
If it is not present, the auto configuration conditional on that class can be discarded and not have an impact on the image startup.
More details on options are discussed <<options,here>>.

===== Add the repository for `spring-graal-native`

If necessary, add the repository for the `spring-graal-native` dependency, as follows:

====
[source,xml,subs="attributes,verbatim"]
----
<repositories>
    <!-- ... -->
    <repository>
        <id>spring-{repository}</id>
        <name>Spring {repository}</name>
        <url>https://repo.spring.io/{repository}</url>
    </repository>
</repositories>
----
====

===== Add and update the appropriate dependencies

The following listing shows the dependencies to add:

====
[source,xml,subs="attributes,verbatim"]
----
<dependencies>
    <!-- ... -->
    <dependency>
        <groupId>org.springframework.experimental</groupId>
        <artifactId>spring-graal-native</artifactId>
        <version>{version}</version>
    </dependency>

    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context-indexer</artifactId>
    </dependency>
</dependencies>
----
====

* What is `spring-graal-native`?
The `spring-graal-native` dependency brings together several components. It includes the GraalVM feature implementation.
It includes the temporary substitutions (a GraalVM term) for patching around issues with some classes whilst we wait for more correct fixes in these classes. 
The feature behaviour is actually driven by a set of annotations that encapsulate boot knowledge that is non obvious from a high level static analysis of the code, for example a particular ImportSelector may required reflective access to a type. This knowledge is also included in the `spring-graal-native` dependency.

* The `spring-context-indexer` has been in Spring for a while.
In a native image, all notion of classpath is lost, so it is not possible to explore the classpath to find components at runtime.
The indexer actually produces a list of components at Java compile time and captures it in a `spring.components` file in the built application.
If Spring starts and finds this file, it uses it instead of attempting to explore the classpath.
The indexer can be used for this whether building a native image or just running your application as a standard Java application.

You should also exclude the `tomcat-embed-websocket` dependency from the `spring-boot-starter-web` for now (we are working on https://github.com/apache/tomcat/pull/274[a Tomcat contribution] to avoid this):

====
[source,xml,subs="attributes,verbatim"]
----
<dependencies>
    <!-- ... -->
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-web</artifactId>
        <exclusions>
            <exclusion>
                <groupId>org.apache.tomcat.embed</groupId>
                <artifactId>tomcat-embed-websocket</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
</dependencies>
----
====

===== Set the `start-class` element

The native image build needs to know the entry point to your application. It does consult a few places to find it.
However, in our sample we should set it in the `properties section` of the `pom.xml` file, as follows:

====
[source,xml]
----
<properties>
    <!-- ... -->
    <start-class>com.example.restservice.RestServiceApplication</start-class>
</properties>
----
====

===== Update the source code

In this sample, are no changes need to be made.
However, in some Boot applications, it may be necessary to make some tweaks to ensure they are not doing anything that is not supported by GraalVM native images.

====== Proxies

The only kind of proxy allowed with native images is a JDK proxy.
It is not possible to use CGLIB or some other kind of generated proxy.
Boot 2.2, added the option to avoid creating these kinds of native image incompatible proxies for configuration class contents and this happens to suit native image compilation.
The enhancement in question is discussed https://github.com/spring-projects/spring-framework/wiki/What%27s-New-in-Spring-Framework-5.x#core-container[here].
Basically, applications need to switch to using `proxyBeanMethods=false` in their configuration annotations.
The framework code has already all moved to this model.

Adapt `RestServiceApplication.java` accordingly:

====
[source,java]
----
@SpringBootApplication(proxyBeanMethods = false)
public class RestServiceApplication {

    public static void main(String[] args) {
        SpringApplication.run(RestServiceApplication.class, args);
    }

}
----
====

==== Build the application

====
[source,bash]
----
mvn -Pgraal clean package
----
====

Did it build cleanly?
If so, the resultant executable is in the target folder named after the `start-class` (in this case, `com.example.restservice.restserviceapplication`).

Did it fail? See the <<troubleshooting>> section.

==== Run the application

To run your application, you need to run the following executable:

====
[source,bash]
----
./target/com.example.restservice.restserviceapplication

...
Mar 18, 2020 3:26:16 PM org.springframework.boot.web.embedded.tomcat.TomcatWebServer start
INFO: Tomcat started on port(s): 8080 (http) with context path ''
Mar 18, 2020 3:26:16 PM org.springframework.boot.StartupInfoLogger logStarted
INFO: Started RestServiceApplication in 0.084 seconds (JVM running for 0.087)
----
====

The startup time is <100ms, compared ~1500ms when starting the fat jar.

Did your application run successfully? If so, good. If not, see the <<troubleshooting>> page.

==== Summary

Hopefully, this section has given you a taste of the process of building native images.
There is much more coming to optimize Spring in all areas: smaller images, reduced memory usage, faster native image compilation, and more.
We are also working with the GraalVM team in all the pitfall areas mentioned earlier.
Across the board, things should only get better.
If you apply these techniques to your own application and have problems, see <<troubleshooting>>.
