[[hybrid]]
=== Using the Hybrid Feature-Agent Mode

This section shows the `spring-graal-native` feature and agent being used together.

This section walks through how to build a `native-image` for a Spring Boot project.
This is a practical guide, so we perform this for real on the https://spring.io/guides/gs/rest-service/[REST service getting started guide].
Unlike the <<feature,feature>> or <<agent,agent>> sections, which show how to use those capabilities standalone, this will use them together in a single project.
With the feature not being able to easily know everything about your application, and the agent missing things and not understanding Spring applications, it can sometimes be useful to use them both together.

==== Download and Install GraalVM

Although the native-image build is going to be invoked through Maven, the agent is shipped with GraalVM, and we need to install it by following {project-home}#install-graalvm-native[these instructions].
Notice that Java8 and Java11 versions are available.
Although either should work, we have had more issues with the Java11 one, so playing it safe would be selecting the Java8 version.

==== Setup the sample project

Just to get ready, clone the sample project, as follows:

====
[source,bash]
----
git clone https://github.com/spring-guides/gs-rest-service
cd gs-rest-service/complete
----
====

You may already be ready to go with your own project.

==== Update the `pom.xml` File

NOTE: Ensure the project uses a supported version of Spring Boot.

Upgrade the project to Spring Boot 2.3.0.M3.

If you use a milestone (or snapshot) of Boot, the following repositories also need to be added to the `pom.xml`:

====
[source,XML]
----
<pluginRepositories>
    <!-- ... -->
    <pluginRepository>
        <id>spring-milestone</id>
        <name>Spring Milestone</name>
        <url>https://repo.spring.io/milestone</url>
    </pluginRepository>
</pluginRepositories>
<repositories>
    <!-- ... -->
    <repository>
        <id>spring-milestone</id>
        <name>Spring Milestone</name>
        <url>https://repo.spring.io/milestone</url>
    </repository>
</repositories>
----
====

===== Add the Maven Plugin

GraalVM provides a Maven plugin that we are going to bring in here.
Paste the following XML into the `pom.xml` file (we use it later to invoke the native image build):

====
[source,XML]
----
<profiles>
  <profile>
    <id>graal</id>
    <build>
      <plugins>
        <plugin>
          <groupId>org.graalvm.nativeimage</groupId>
          <artifactId>native-image-maven-plugin</artifactId>
          <version>20.0.0</version>
          <configuration>
            <buildArgs>-Dspring.graal.remove-unused-autoconfig=true --no-fallback --allow-incomplete-classpath --report-unsupported-elements-at-runtime -H:+ReportExceptionStackTraces --no-server</buildArgs>
          </configuration>
          <executions>
            <execution>
              <goals>
                <goal>native-image</goal>
              </goals>
              <phase>package</phase>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-maven-plugin</artifactId>
        </plugin>
      </plugins>
    </build>
  </profile>
</profiles>
----
====

The important part is the `<buildArgs>..</buildArgs>` block that shows the options we are passing to the `native-image` operation and the `spring-graal-native` feature.
Those prefixed `-D` are aimed at the feature.

NOTE: Notice the `--no-server` option.
Like a Gradle daemon, the server here is supposed to help accelerate subsequent builds.
Unfortunately, there is an https://github.com/oracle/graal/issues/1952[issue] where the server causes different results to come out of the compilation.
In particular, we have seen logging disappear if the server is used to aid compilation.
Hence using the server to aid compilation is turned off here.

We can use the `-Dspring.graal.remove-unused-autoconfig=true` option to evaluate some of the Spring Boot conditions at image-build time.
For example, it applies to `@ConditionalOnClass`.
Because `native-image` runs at a point when the full classpath is known, we can know for certain if a class is around.
If it is not around, the auto-configuration conditional on that class can be discarded and not have an impact on the image startup. More details on options are discussed <<options,here>>.

===== Add the Feature and Appropriate Configuration Dependencies

====
[source,XML]
----
<dependency>
    <groupId>org.springframework.experimental</groupId>
    <artifactId>spring-graal-native-feature</artifactId>
    <version>0.6.0.BUILD-SNAPSHOT</version>
</dependency>

<dependency>
    <groupId>org.springframework.experimental</groupId>
    <artifactId>spring-graal-native-configuration</artifactId>
    <version>0.6.0.BUILD-SNAPSHOT</version>
</dependency>

<dependency>
  <groupId>org.springframework</groupId>
  <artifactId>spring-context-indexer</artifactId>
</dependency>
----
====

* The `spring-context-indexer` has been in Spring for a while.
In a `native-image`, all notion of classpath is lost, so it is not possible to explore the classpath to find components at runtime.
The indexer actually produces a list of components at Java compile time and captures it in a `spring.components` file in the built application.
If Spring starts and finds this file, it uses it instead of attempting to explore the classpath.
The indexer can be used for this whether building a native image or just running your application as a standard Java application.

* What is `spring-graal-native-configuration`?
The `spring-graal-native-feature` behavior is partially driven by hints for any reflective or resource accesses that are not obvious from what it can see in the Spring application being built into a native image.
The `spring-graal-native-configuration` is once such source of hints.
These hints captur what needs to be reflectively accessible or loadable as resources that is not obvious from a basic analysis of the application.

===== Set the `start-class` Element

The native image build needs to know the entry point to your application.
It does consult a few places to find it.
However, in our sample we should set it in the properties section of the `pom.xml` file, as follows:

====
[source,XML]
----
<start-class>com.example.restservice.RestServiceApplication</start-class>
----
====

===== Update the Source Code

In the case of this sample, there are no changes to be made.
However, in some Boot applications, you may need to make some tweaks to ensure that they are not doing anything that is not supported by GraalVM native images.

====== Proxies

The only kind of proxy allowed with native images is a JDK proxy.
It is not possible to use CGLIB or some other kind of generated proxy.
Boot 2.2 added the option to avoid creating these kinds of `native-image` incompatible proxies for configuration class contents, and this happens to suit native-image compilation.
The enhancement in question is discussed https://github.com/spring-projects/spring-framework/wiki/What's-New-in-Spring-Framework-5.x#core-container[here].
Basically, applications need to switch to using `proxyBeanMethods=false` in their configuration annotations.
The framework code has already all moved to this model.
The following example is from the `webflux-netty` sample:

====
[source,Java]
----
@SpringBootApplication(proxyBeanMethods = false)
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

	@RestController
	class Foo {

		@GetMapping("/")
		public String greet() {
			return "hi!";
		}
	}

}
----
====

===== Create a Location for the Generated Configuration

When run with the agent, it needs somewhere to store the `.json` files it computes.
This can be anywhere, but that location needs to be under a location of `META-INF/native-image` and on the classpath so that the native image operation automaticallys pick it up.
If we want to keep this configuration around, we can generate it straight into the project (and perhaps store it in version control), as follows:

====
[source,bash]
----
mkdir -p src/main/resources/META-INF/native-image
----
====

NOTE: The "`proper`" location is perhaps a `<groupid>/<artifactid>` location below `native-image` but we keep it simple here for now.

===== Run the Application with the Agent

The following commands run the application with the agent:

====
[source,bash]
----
mvn clean package
java -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image \
  -jar target/rest-service-0.0.1-SNAPSHOT.jar
----
====

It should run as normal.

IMPORTANT: While it is up to you to make sure you exercise any codepaths you want to ensure are covered by the native image that will be built, exercising those paths may cause extra reflection access or resource loading or other issues.

Shutdown the app.

Notice that the files that now exist in the folder:

====
[source,bash]
----
ls -l src/main/resources/META-INF/native-image
total 256
-rw-r--r--  1 foo  bar      4 18 Mar 18:59 jni-config.json
-rw-r--r--  1 foo  bar   1057 18 Mar 18:59 proxy-config.json
-rw-r--r--  1 foo  bar  98309 18 Mar 18:59 reflect-config.json
-rw-r--r--  1 foo  bar  17830 18 Mar 18:59 resource-config.json
----
====

Build a native image for the application, as follows:

====
[source,bash]
----
mvn -Pgraal clean package
----
====

This uses the feature to do some computation, but it also uses the input generated by the agent.

Did it build cleanly?
If so, the resultant executable is in the target folder named after the `start-class` (in this case, `com.example.restservice.RestServiceApplication`).

Did it fail?
See the <<troubleshooting>> page.
As of this writing, this step works.

===== Run the Application

To run the application, run the following executable:

====
[source,bash]
----
./target/com.example.restservice.RestServiceApplication

...
Mar 18, 2020 3:26:16 PM org.springframework.boot.web.embedded.tomcat.TomcatWebServer start
INFO: Tomcat started on port(s): 8080 (http) with context path ''
Mar 18, 2020 3:26:16 PM org.springframework.boot.StartupInfoLogger logStarted
INFO: Started RestServiceApplication in 0.084 seconds (JVM running for 0.087)
----
====

The startup time is <100ms, compared ~1500ms when starting the fat jar.

Did your application run successfully?
If so, good.
If not, see the <<troubleshooting>> page.

===== Summary

Hopefully, this section has given you a taste of the process of building native images.
There is much more coming to optimize Spring in all areas: smaller images, reduced memory usage, faster native image compilation, and more.
We are also working with the Graal team in all the pitfall areas described earlier.
Things across the board should only get better.
If you apply these techniques to your own application and have problems, see <<troubleshooting>>.
