[[build-setup]]
== Build Setup
This section covers how to configure your build for <<build-setup-maven,Maven>> or <<build-setup-gradle,Gradle>>.
You'll also learn more about <<build-setup-modes,the types of sources generated and how they're used>>

[[build-setup-maven]]
=== Maven

The plugin should be declared in your `pom.xml` file:

[source,xml,subs="attributes,verbatim"]
.Maven
----
<dependencies>
	<!-- This is a mandatory dependency for your application -->
	<groupId>org.springframework.experimental</groupId>
	<artifactId>spring-native</artifactId>
</dependencies>
<build>
    <plugins>
        <!-- ... -->
        <plugin>
            <groupId>org.springframework.experimental</groupId>
            <artifactId>spring-aot-maven-plugin</artifactId>
            <version>{version}</version>
            <executions>
                <execution>
                    <id>generate</id>
                    <goals>
                        <goal>generate</goal>
                    </goals>
                </execution>
                <execution>
                    <id>test-generate</id>
                    <goals>
                        <goal>test-generate</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
----

Maven goals `spring-aot:generate` (`prepare-package` phase) and `spring-aot:test-generate` (`process-test-classes` phase) are automatically invoked in the Maven lifecycle when using the `mvn verify` or `mvn package` commands.
The `spring-aot:*` goals are not meant to be called directly since they rely on other parts of the lifecycle.
Sources are generated in `target/generated-runtime-sources/spring-aot/` and test sources in `target/generated-runtime-test-sources/spring-aot/`.

NOTE: When `spring-aot-maven-plugin` is applied, `mvn test -DspringAot=false` runs tests in regular mode while `mvn test` generates related sources and run tests in AOT mode.

Configuration can be performed if needed within the `<configuration>` element, for example to remove SpEL support at build-time if your application does not use it in order to optimize the footprint:

[source,xml,subs="attributes,verbatim"]
----
<configuration>
    <removeSpelSupport>true</removeSpelSupport>
</configuration>
----

See <<build-setup-configuration>> for a list of the configuration options available.



[[build-setup-gradle]]
=== Gradle

You can configure the Gradle Spring AOT plugin by declaring first the plugin repositories in your `settings.gradle(.kts)` file:

[source,groovy,subs="attributes,verbatim",role="primary"]
.Gradle Groovy
----
pluginManagement {
    repositories {
        // ...
        maven { url 'https://repo.spring.io/{spring-native-repo}' }
    }
}
----
[source,Kotlin,subs="attributes,verbatim",role="secondary"]
.Gradle Kotlin
----
pluginManagement {
    repositories {
        // ...
        maven { url = uri("https://repo.spring.io/{spring-native-repo}") }
    }
}
----

[source,groovy,subs="attributes,verbatim",role="primary"]
.Gradle Groovy
----
plugins {
    // ...
    id 'org.springframework.experimental.aot' version '{version}'
}
----
[source,Kotlin,subs="attributes,verbatim",role="secondary"]
.Gradle Kotlin
----
plugins {
    // ...
    id("org.springframework.experimental.aot") version "{version}"
}
----

The plugin creates two `SourceSets` for testing and running the application: "aot" and "aotTest".
The resulting classes and resources are automatically added to the runtime classpath of the application when running the `aotTest`, `bootRun` and `bootJar` tasks.
You can also call directly `generateAot` and `generateTestAot` tasks to perform only the generation.

Sources are generated in `build/generated/runtimeSources/aotMain/`, `build/generated/resources/aotMain/` and test sources in `build/generated/runtimeSources/aotTest/`, `build/generated/resources/aotTest/`.

NOTE: `test` task runs tests in regular mode while `aotTest` task generates related sources and run tests in AOT mode.

Configuration can be performed if needed using the `springAot` DSL extension, for example to remove SpEL support at build-time if your application does not use it in order to optimize the footprint:

[source,groovy,subs="attributes,verbatim",role="primary"]
.Gradle Groovy
----
springAot {
	removeSpelSupport = true
}
----
[source,Kotlin,subs="attributes,verbatim",role="secondary"]
.Gradle Kotlin
----
springAot {
	removeSpelSupport.set(true)
}
----

Here is a complete code sample showing all the default values and how to set them:

[source,groovy,subs="attributes,verbatim",role="primary"]
.Gradle Groovy
----
import org.springframework.aot.gradle.dsl.AotMode

// ...

springAot {
	mode = AotMode.NATIVE
	debugVerify = false
	removeXmlSupport = true
	removeSpelSupport = false
	removeYamlSupport = false
	removeJmxSupport = true
	verify = true
}
----
[source,Kotlin,subs="attributes,verbatim",role="secondary"]
.Gradle Kotlin
----
import org.springframework.aot.gradle.dsl.AotMode

// ...

springAot {
	mode.set(AotMode.NATIVE)
	debugVerify.set(false)
	removeXmlSupport.set(true)
	removeSpelSupport.set(false)
	removeYamlSupport.set(false)
	removeJmxSupport.set(true)
	verify.set(true)
}
----

NOTE: The non-idomatic `property.set(...)` syntax in the Gradle Kotlin DSL is due to https://github.com/gradle/gradle/issues/9268[gradle#9268], feel free to vote for this issue.

See <<build-setup-configuration>> for more details on the configuration options.



[[build-setup-configuration]]
=== AOT Configuration

The Spring AOT plugins allow you to express opinions about the source generation process.
Here are all the options available:

* `mode` switches how much configuration the plugin actually provides to the native image compiler:
** `native` (default) generates AOT Spring factories, application context bootstrap, native configuration, native-image.properties as well as substitutions.
** `native-agent` is designed to be used with the configuration generated by the tracing agent. Generates AOT Spring factories, application context bootstrap, native-image.properties as well as substitutions.

* *`removeXmlSupport` is set to `true` by default to optimize the footprint, setting it to `false` restores Spring XML support (XML converters, codecs and XML application context support).*

* `removeSpelSupport` is set to `false` by default, setting it to `true` removes Spring SpEL support to optimize the footprint (should be used only on applications not requiring SpEL).

* `removeYamlSupport` is set to `false` by default, setting it to `true` removes Spring Boot Yaml support to optimize the footprint.

* *`removeJmxSupport` is set to `true` by default to optimize the footprint, setting it to `false` restores Spring Boot JMX support.*

* `verify` is set to `true` by default and perform some automated verification to ensure your application is native compliant, setting it to `false` switches off the verifications.

* `debugVerify` is set to `false` by default and enables verification debug when set to `true`.

* `mainClass` allows to specify a main class, useful when multiple ones are present.

* `applicationClass` allows to specify an application class (typically annotated with `@SpringBootApplication`), useful when multiple ones are present.

==== Debugging the source generation

The Spring AOT plugins spawns a new process to perform the source generation.
To remote debug this process, you can set a debug System property on the command line; then, the source generation process launches with a listener accepting a remote debugger on port `8000` for Maven or `5005` for Gradle.

[source,bash,role="primary"]
.Maven
----
$ # use the port 8000 by default
$ mvn spring-aot:generate -Dspring.aot.debug=true
$ # configure custom debug options
$ mvn spring-aot:generate -Dspring.aot.debug=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=8000
$ mvn spring-aot:generate -Dspring.aot.debug="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=9000 -Xnoagent"
----
[source,bash,role="secondary"]
.Gradle
----
$ # use the port 5005 by default
$ ./gradlew generateAot -Dspring.aot.debug=true
$ # configure a custom port
$ ./gradlew generateAot -Dspring.aot.debug=true -Dspring.aot.debug.port=9000
----

If the need to debug the plugins that are involved before the source generation, use the regular related commands:

[source,bash,role="primary"]
.Maven
----
$ # use the port 8000 by default
$ mvnDebug spring-aot:generate
----
[source,bash,role="secondary"]
.Gradle
----
$ # use the port 5005 by default
$ ./gradlew generateAot -Dorg.gradle.debug=true --no-daemon
----


[[build-setup-modes]]
=== AOT Modes

The generated sources are automatically used by the native image compilation, but are not used by default when running your application with a JVM.
This means that running the application or its tests from the IDE or the command line will not involve those classes.

Any application using Spring AOT can use the `springAot` System property in order to use the AOT classes with a regular JVM.
This is mainly useful for debugging purposes in case of issues during native image generation.

NOTE: When AOT mode is enabled, Spring Boot Developer Tools are ignored as they are not compatible with an AOT approach.

You can set such a property when running an executable Jar from the command line:

[source,bash,subs="attributes,verbatim"]
----
java -DspringAot=true -jar myapplication-0.0.1-SNAPSHOT.jar
----

==== IDEs

In IDEs, you can specify `-DspringAot=true` when running the application to enable the AOT mode. It requires AOT generation has been invoked before manually via Maven or Gradle.

WARNING: With IntelliJ IDEA Gradle support, be aware running application in AOT mode is broken in IDEA when delegated to Gradle, see https://youtrack.jetbrains.com/issue/IDEA-287067[IDEA-287067] related issue. As a workaround, you can go to "File -> Plugins ... -> Build, Execution, Deployment -> Build tools -> Gradle" and change "Build and run using" from "Gradle" to "IntelliJ IDEA".

==== Plugins

For running an application with `gradle bootRun` or `mvn spring-boot:run`, configure your build as following:

[source,xml,subs="attributes,verbatim",role="primary"]
.Maven
----
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <!-- ... -->
        <systemPropertyVariables>
            <springAot>true</springAot>
        </systemPropertyVariables>
    </configuration>
</plugin>
----
[source,subs="attributes,verbatim",role="secondary"]
.Gradle Groovy
----
bootRun {
	systemProperty 'springAot', 'true'
}
----
[source,Kotlin,subs="attributes,verbatim",role="secondary"]
.Gradle Kotlin
----
tasks.getByName<BootRun>("bootRun") {
	systemProperty("springAot", "true")
}
----
