[[getting-started-native-build-tools]]
=== Getting started with Native Build Tools

This section gives you a practical overview of building a Spring Boot native application using the {graalvm-native-buildtools}[GraalVM native build tools].
This is a practical guide that uses the https://spring.io/guides/gs/rest-service/[RESTful Web Service getting started guide].

[[getting-started-native-image-system-requirements]]
==== System Requirements

A number of {graalvm-native-docs}/#prerequisites[prerequisites] are required before installing the GraalVM `native-image` compiler.
You then need a local installation of the native image compiler.

There are various distributions of the `native-image` compiler available, here we focus on those 2 ones:

* https://www.graalvm.org/[GraalVM] CE based on the https://github.com/oracle/graal[GraalVM open-source repository] and LabsJDK
* Bellsoft https://bell-sw.com/pages/liberica-native-image-kit/[Liberica Native Image Kit] (NIK) based on the https://github.com/oracle/graal[GraalVM open-source repository] and Liberica JDK

===== Linux and MacOS

To install the native image compiler on MacOS or Linux, we recommend using https://sdkman.io/[SDKMAN]:

* https://sdkman.io/install[Install SDKMAN].
* Install a GraalVM native-image distribution, either GraalVM CE (`grl` suffix) or Bellsoft Liberica NIK (`nik` suffix), here we go with Liberica NIK Java 11 variant: `sdk install java {graalvm-version}.r11-nik`
* Make sure to use the newly installed JDK with `sdk use java {graalvm-version}.r11-nik`
* Run `gu install native-image` to bring in the native-image extensions to the JDK.

Alternatively, you can manually install builds from https://www.graalvm.org/downloads/[GraalVM] or https://bell-sw.com/pages/downloads/native-image-kit/[Liberica NIK]. Don't forget to set `JAVA_HOME` / `PATH` appropriately if needed and to run `gu install native-image` to bring in the native-image extensions.

===== Windows

On Windows, follow https://medium.com/graalvm/using-graalvm-and-native-image-on-windows-10-9954dc071311[those instructions] to install either https://www.graalvm.org/downloads/[GraalVM] or https://bell-sw.com/pages/downloads/native-image-kit/[Liberica NIK], Visual Studio Build Tools and Windows SDK. Due to a well-known https://docs.microsoft.com/en-US/troubleshoot/windows-client/shell-experience/command-line-string-limitation[Windows limitations related command-line maximum length], make sure to use x64 Native Tools Command Prompt instead of the regular Windows command line to run Maven or Gradle plugins.

==== Sample Project Setup

The completed "RESTful Web Service" guide can be retrieved using the following commands:


[source,bash]
----
git clone https://github.com/spring-guides/gs-rest-service
cd gs-rest-service/complete
----


===== Validate Spring Boot version

IMPORTANT: Spring Native {version} only supports Spring Boot {spring-boot-version}, so change the version if necessary.

[source,xml,subs="attributes,verbatim",role="primary"]
.Maven
----
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>{spring-boot-version}</version>
    <relativePath/>
</parent>
----
[source,groovy,subs="attributes,verbatim",role="secondary"]
.Gradle Groovy
----
plugins {
    id 'org.springframework.boot' version '{spring-boot-version}'
    // ...
}
----
[source,Kotlin,subs="attributes,verbatim",role="secondary"]
.Gradle Kotlin
----
plugins {
    id("org.springframework.boot") version "{spring-boot-version}"
    // ...
}
----


===== Add the Spring Native dependency

`org.springframework.experimental:spring-native` provides native configuration APIs like `@NativeHint` as well as other mandatory classes required to run a Spring application as a native image.


[source,xml,subs="attributes,verbatim",role="primary"]
.Maven
----
<dependencies>
    <!-- ... -->
    <dependency>
        <groupId>org.springframework.experimental</groupId>
        <artifactId>spring-native</artifactId>
        <version>{version}</version>
    </dependency>
</dependencies>
----
[source,groovy,subs="attributes,verbatim",role="secondary"]
.Gradle Groovy
----
// No need to add the spring-native dependency explicitly with Gradle, the Spring AOT plugin will add it automatically.
----
[source,Kotlin,subs="attributes,verbatim",role="secondary"]
.Gradle Kotlin
----
// No need to add the spring-native dependency explicitly with Gradle, the Spring AOT plugin will add it automatically.
----


===== Add the Spring AOT plugin

The <<spring-aot,Spring AOT>> plugin performs ahead-of-time transformations required to improve native image compatibility and footprint.

[source,xml,subs="attributes,verbatim",role="primary"]
.Maven
----
<build>
    <plugins>
        <!-- ... -->
        <plugin>
            <groupId>org.springframework.experimental</groupId>
            <artifactId>spring-aot-maven-plugin</artifactId>
            <version>{version}</version>
            <executions>
                <execution>
                    <id>generate</id>
                    <goals>
                        <goal>generate</goal>
                    </goals>
                </execution>
                <execution>
                    <id>test-generate</id>
                    <goals>
                        <goal>test-generate</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
----
[source,subs="attributes,verbatim",role="secondary"]
.Gradle Groovy
----
plugins {
    // ...
    id 'org.springframework.experimental.aot' version '{version}'
}
----
[source,Kotlin,subs="attributes,verbatim",role="secondary"]
.Gradle Kotlin
----
plugins {
    // ...
    id("org.springframework.experimental.aot") version "{version}"
}
----


The plugin provides a number of options to customize the transformations, see <<aot>> for more details.

===== Add the native build tools plugin

GraalVM provides {graalvm-native-buildtools}[Gradle and Maven plugins] to invoke the native image compiler from your build.
The following example adds a `native` profile that triggers the plugin during the `package` phase:

[source,xml,subs="attributes,verbatim",role="primary"]
.Maven
----
<profiles>
        <profile>
            <id>native</id>
            <dependencies>
                <!-- Required with Maven Surefire 2.x -->
                <dependency>
                    <groupId>org.junit.platform</groupId>
                    <artifactId>junit-platform-launcher</artifactId>
                    <scope>test</scope>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>{graalvm-native-buildtools-version}</version>
                        <extensions>true</extensions>
                        <executions>
                            <execution>
                                <id>build-native</id>
                                <goals>
                                    <goal>build</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                            <execution>
                                <id>test-native</id>
                                <goals>
                                    <goal>test</goal>
                                </goals>
                                <phase>test</phase>
                            </execution>
                        </executions>
                        <configuration>
                            <!-- ... -->
                        </configuration>
                    </plugin>
                    <!-- Avoid a clash between Spring Boot repackaging and native-maven-plugin -->
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <configuration>
                            <classifier>exec</classifier>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
----
[source,subs="attributes,verbatim",role="secondary"]
.Gradle Groovy
----
// The GraalVM native build tools plugin is applied and configured automatically
----
[source,Kotlin,subs="attributes,verbatim",role="secondary"]
.Gradle Kotlin
----
// The GraalVM native build tools plugin is applied and configured automatically
----

NOTE: When used with Spring AOT, Native Build Tools Gradle toolchain support is disabled by default in order to avoid current limitations related to identifying in a reliable way JDK with native capabilities. See https://github.com/gradle/gradle/issues/18896[this related Gradle issue].

===== Maven Repository

Configure your build to include the {spring-native-repo} repository for the `spring-native` dependency, and the Maven Central one with Gradle for the native build tools one as follows:


[source,xml,subs="attributes,verbatim",role="primary"]
.Maven
----
<repositories>
    <!-- ... -->
    <repository>
        <id>spring-{spring-native-repo}</id>
        <name>Spring {spring-native-repo}</name>
        <url>https://repo.spring.io/{spring-native-repo}</url>
    </repository>
</repositories>
----
[source,subs="attributes,verbatim",role="secondary"]
.Gradle Groovy
----
repositories {
    // ...
    mavenCentral()
    maven { url 'https://repo.spring.io/{spring-native-repo}' }
}
----
[source,Kotlin,subs="attributes,verbatim",role="secondary"]
.Gradle Kotlin
----
repositories {
    // ...
    mavenCentral()
    maven { url = uri("https://repo.spring.io/{spring-native-repo}") }
}
----


Same thing for the plugins:


[source,xml,subs="attributes,verbatim",role="primary"]
.Maven
----
<pluginRepositories>
    <!-- ... -->
    <pluginRepository>
        <id>spring-{spring-native-repo}</id>
        <name>Spring {spring-native-repo}</name>
        <url>https://repo.spring.io/{spring-native-repo}</url>
    </pluginRepository>
</pluginRepositories>
----
[source,subs="attributes,verbatim",role="secondary"]
.Gradle Groovy
----
pluginManagement {
    repositories {
        // ...
        mavenCentral()
        maven { url 'https://repo.spring.io/{spring-native-repo}' }
    }
}
----
[source,Kotlin,subs="attributes,verbatim",role="secondary"]
.Gradle Kotlin
----
pluginManagement {
    repositories {
        // ...
        mavenCentral()
        maven { url = uri("https://repo.spring.io/{spring-native-repo}") }
    }
}
----


==== Build the native application

The native application can be built as follows:

[source,bash,role="primary"]
.Maven
----
$ mvn -Pnative -DskipTests package
----
[source,bash,role="secondary"]
.Gradle Groovy
----
$ gradle nativeCompile
----
[source,bash,role="secondary"]
.Gradle Kotlin
----
$ gradle nativeCompile
----

This command creates a native executable containing your Spring Boot application in the `target` directory.

==== Run the native application

To run your application, invoke the following:


[source,bash]
----
$ target/gs-rest-service
----


The startup time should be less than `100ms`, compared to the roughly `1500ms` when starting the application on the JVM.

Now that the service is up, visit `http://localhost:8080/greeting`, where you should see:


[source,json]
----
{"id":1,"content":"Hello, World!"}
----

==== Test the native application

The native application can be tested as follows:

[source,bash,role="primary"]
.Maven
----
$ mvn -Pnative test
----
[source,bash,role="secondary"]
.Gradle Groovy
----
$ gradle nativeTest
----
[source,bash,role="secondary"]
.Gradle Kotlin
----
$ gradle nativeTest
----

You can find more details about the native build tools https://github.com/graalvm/native-build-tools[here].
