[[getting-started-native-image]]
=== Getting started with native image Maven plugin

This section walks through how to build a Spring Boot native application with {graalvm-native-docs}/NativeImageMavenPlugin/[native image Maven plugin].
This is a practical guide, so we perform this for real on the https://spring.io/guides/gs/rest-service/[REST service getting started guide].

==== Prerequisites

Before installing the GraalVM `native-image` compiler, install {graalvm-native-docs}/#prerequisites[the prerequisites] (pay attention to the Windows ones if you are using that platform).
You then need a local installation of the native image compiler.

On Mac or Linux, you can use https://sdkman.io/[SDKMAN] to easily install GraalVM and switch between JDKs:

- https://sdkman.io/install[Install SDKMAN]
- Install GraalVM with `sdk install java {graalvm-version}.r8-grl` for Java 8 or `sdk install java {graalvm-version}.r11-grl` for Java 11
- Make sure to use the newly installed JDK with `sdk use java {graalvm-version}.r8-grl` or `sdk use java {graalvm-version}.r11-grl`
- Run `gu install native-image` to bring in the native-image extensions to the JDK.

Alternatively or if you are on Windows, you can download and install manually GraalVM builds:

- Install GraalVM {graalvm-version} from https://www.graalvm.org/downloads/[here].
- Set `JAVA_HOME` and `PATH` appropriately for that GraalVM version.
- Run `gu install native-image` to bring in the native-image extensions to the JDK.

==== Set up the sample project

Here we use the getting started REST service guide, the following commands install it:

====
[source,bash]
----
git clone https://github.com/spring-guides/gs-rest-service
cd gs-rest-service/complete
----
====

===== Update the `pom.xml` file

IMPORTANT: Only Spring Boot {spring-boot-version} is supported, so change the version if necessary.

====
[source,xml,subs="attributes,verbatim"]
----
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>{spring-boot-version}</version>
    <relativePath/> <!-- lookup parent from repository -->
</parent>
----
====

===== `spring-native` dependency

The `spring-native` dependency provides native configuration APIs like `@NativeHint` as well as other mandatory classes required to run a Spring application as a native image.

====
[source,xml,subs="attributes,verbatim"]
----
<dependencies>
    <!-- ... -->
    <dependency>
        <groupId>org.springframework.experimental</groupId>
        <artifactId>spring-native</artifactId>
        <version>{version}</version>
    </dependency>
</dependencies>
----
====

===== Add the `spring-aot-maven-plugin`

This plugin will perform ahead-of-time transformations in order to improve native image compatibility and footprint.
We do not put it in the `native-image` profile defined below because these transformations also benefit application run on a JVM.

====
[source,xml,subs="attributes,verbatim"]
----
<build>
    <plugins>
        <!-- ... -->
        <plugin>
            <groupId>org.springframework.experimental</groupId>
            <artifactId>spring-aot-maven-plugin</artifactId>
            <version>{version}</version>
            <executions>
                <execution>
                    <id>test-generate</id>
                    <goals>
                        <goal>test-generate</goal>
                    </goals>
                </execution>
                <execution>
                    <id>generate</id>
                    <goals>
                        <goal>generate</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
----
====

See <<configuring-spring-aot>> for more details about the configuration.

===== Add the native-image profile

GraalVM provides {graalvm-native-docs}/NativeImageMavenPlugin/[native-image-maven-plugin] which can invoke the native image compiler from Maven.
Paste the following XML into the `pom.xml` file (we use it later to invoke the native image build):

====
[source,xml,subs="attributes,verbatim"]
----
<profiles>
  <profile>
    <id>native-image</id>
    <build>
      <plugins>
        <plugin>
          <groupId>org.graalvm.nativeimage</groupId>
          <artifactId>native-image-maven-plugin</artifactId>
          <version>{graalvm-version}</version>
          <configuration>
            <!-- The native image build needs to know the entry point to your application -->
            <mainClass>com.example.restservice.RestServiceApplication</mainClass>
          </configuration>
          <executions>
            <execution>
              <goals>
                <goal>native-image</goal>
              </goals>
              <phase>package</phase>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </build>
  </profile>
</profiles>
----
====

In order to avoid a clash between Spring Boot repackaging and `native-image-maven-plugin` you need to specify a classifier on Spring Boot plugin.

====
[source,xml,subs="attributes,verbatim"]
----
<plugins>
    <!-- ... -->
    <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
            <classifier>exec</classifier>
        </configuration>
    </plugin>
</plugins>
----
====

===== Add the repositories

If necessary, add the repository for the `spring-native` dependency, as follows:

====
[source,xml,subs="attributes,verbatim"]
----
<repositories>
    <!-- ... -->
    <repository>
        <id>spring-{repository}</id>
        <name>Spring {repository}</name>
        <url>https://repo.spring.io/{repository}</url>
    </repository>
</repositories>
----
====

And for plugins:
====
[source,xml,subs="attributes,verbatim"]
----
<pluginRepositories>
    <pluginRepository>
        <id>spring-{repository}</id>
        <name>Spring {repository}</name>
        <url>https://repo.spring.io/{repository}</url>
    </pluginRepository>
</pluginRepositories>
----
====

==== Build the native application

Building the native application is as simple as running:
====
[source,bash]
----
mvn -Pnative-image clean package
----
====

IMPORTANT: On Windows make sure to use x64 Native Tools Command Prompt as recommended in {graalvm-native-docs}/#prerequisites[GraalVM native-image prerequisites].

This will create a native executable containing your Spring Boot application.

==== Run the native application

To run your application, you need to run the previously created container image:

====
[source,bash]
----
target/com.example.restservice.restserviceapplication
----
====

The startup time should be <100ms, compared to ~1500ms when starting the fat jar.

Now that the service is up, visit http://localhost:8080/greeting, where you should see:

====
[source,json]
----
{"id":1,"content":"Hello, World!"}
----
====

See <<spring-aot>> for additional steps to configure properly the plugin in your IDE.



