[[getting-started-native-image]]
=== Getting started with native image Maven plugin

This section gives you a practical overview of building a Spring Boot native application using the {graalvm-native-docs}/NativeImageMavenPlugin/[native image Maven plugin].
This is a practical guide that uses the https://spring.io/guides/gs/rest-service/[RESTful Web Service getting started guide].

NOTE: There is not yet an official native image Gradle plugin, that's why this section is only about Maven. You can vote and subscribe to https://github.com/oracle/graal/issues/3302[graal/issue3302] if you are interested about building native images with Gradle without <<getting-started-buildpacks, using Buildpacks>>.

==== System Requirements

A number of {graalvm-native-docs}/#prerequisites[prerequisites] are required before installing the GraalVM `native-image` compiler.
You then need a local installation of the native image compiler.

To install the native image compiler on MacOS or Linux, we recommend using https://sdkman.io/[SDKMAN]:

* https://sdkman.io/install[Install SDKMAN].
* Install GraalVM with `sdk install java {graalvm-version}.r8-grl` for Java 8 or `sdk install java {graalvm-version}.r11-grl` for Java 11.
* Make sure to use the newly installed JDK with `sdk use java {graalvm-version}.r8-grl` or `sdk use java {graalvm-version}.r11-grl`.
* Run `gu install native-image` to bring in the native-image extensions to the JDK.

Alternatively or if you are on Microsoft Windows, you can manually install GraalVM builds as follows:

* Download https://www.graalvm.org/downloads/[GraalVM {graalvm-version}].
* Set `JAVA_HOME` and `PATH` appropriately.
* Run `gu install native-image` to bring in the native-image extensions to the JDK.

==== Sample Project Setup

The completed "RESTful Web Service" guide can be retrieved using the following commands:


[source,bash]
----
git clone https://github.com/spring-guides/gs-rest-service
cd gs-rest-service/complete
----


===== Validate Spring Boot version

IMPORTANT: Spring Native {version} only supports Spring Boot {spring-boot-version}, so change the version if necessary.

[source,xml,subs="attributes,verbatim"]
----
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>{spring-boot-version}</version>
    <relativePath/>
</parent>
----


===== Add the Spring Native dependency

`org.springframework.experimental:spring-native` provides native configuration APIs like `@NativeHint` as well as other mandatory classes required to run a Spring application as a native image.


[source,xml,subs="attributes,verbatim"]
----
<dependencies>
    <!-- ... -->
    <dependency>
        <groupId>org.springframework.experimental</groupId>
        <artifactId>spring-native</artifactId>
        <version>{version}</version>
    </dependency>
</dependencies>
----


===== Add the Spring AOT plugin

The Spring AOT plugin performs ahead-of-time transformations required to improve native image compatibility and footprint.

TIP: The transformations also apply to the JVM so this can be applied regardless.


[source,xml,subs="attributes,verbatim"]
----
<build>
    <plugins>
        <!-- ... -->
        <plugin>
            <groupId>org.springframework.experimental</groupId>
            <artifactId>spring-aot-maven-plugin</artifactId>
            <version>{version}</version>
            <executions>
                <execution>
                    <id>test-generate</id>
                    <goals>
                        <goal>test-generate</goal>
                    </goals>
                </execution>
                <execution>
                    <id>generate</id>
                    <goals>
                        <goal>generate</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
----


The plugin provides a number of options to customize the transformations, see <<spring-aot-configuration>> for more details.

===== Enable native image support

GraalVM provides a {graalvm-native-docs}/NativeImageMavenPlugin/[Maven Plugin] to invoke the native image compiler from your Maven build.
The following example adds a `native-image` profile that triggers the plugin during the `package` phase:


[source,xml,subs="attributes,verbatim"]
----
<profiles>
  <profile>
    <id>native-image</id>
    <build>
      <plugins>
        <plugin>
          <groupId>org.graalvm.nativeimage</groupId>
          <artifactId>native-image-maven-plugin</artifactId>
          <version>{graalvm-version}</version>
          <executions>
            <execution>
              <goals>
                <goal>native-image</goal>
              </goals>
              <phase>package</phase>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </build>
  </profile>
</profiles>
----


In a default Spring Boot setup, the `spring-boot-maven-plugin` also runs during the `package` phase and replaces the regular jar by the repackaged, executable jar.
To avoid a clash between the two plugins, make sure to specify a classifier like `exec` below for the executable jar:


[source,xml,subs="attributes,verbatim"]
----
<plugins>
    <!-- ... -->
    <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
            <classifier>exec</classifier>
        </configuration>
    </plugin>
</plugins>
----


===== Maven Repository

Configure your build to include the required repository for the `spring-native` dependency, as follows:


[source,xml,subs="attributes,verbatim"]
----
<repositories>
    <!-- ... -->
    <repository>
        <id>spring-{spring-native-repo}</id>
        <name>Spring {spring-native-repo}</name>
        <url>https://repo.spring.io/{spring-native-repo}</url>
    </repository>
</repositories>
----


The Spring AOT plugin also requires a dedicated plugin repository:


[source,xml,subs="attributes,verbatim"]
----
<pluginRepositories>
    <!-- ... -->
    <pluginRepository>
        <id>spring-{spring-native-repo}</id>
        <name>Spring {spring-native-repo}</name>
        <url>https://repo.spring.io/{spring-native-repo}</url>
    </pluginRepository>
</pluginRepositories>
----


==== Build the native application

The native application can be built as follows:

[source,bash]
----
$ mvn -Pnative-image package
----

NOTE: During the native compilation, you will see a lot of `WARNING: Could not register reflection metadata` messages. They are expected and will be removed in a future version, see https://github.com/spring-projects-experimental/spring-native/issues/502#issuecomment-786933142[#502] for more details.

IMPORTANT: On Windows make sure to use x64 Native Tools Command Prompt as recommended in the {graalvm-native-docs}/#prerequisites[GraalVM native-image prerequisites].

This command creates a native executable containing your Spring Boot application in the `target` directory.

==== Run the native application

To run your application, invoke the following:


[source,bash]
----
$ target/com.example.restservice.restserviceapplication
----


The startup time should be less than `100ms`, compared to the roughly `1500ms` when starting the application on the JVM.

Now that the service is up, visit `http://localhost:8080/greeting`, where you should see:


[source,json]
----
{"id":1,"content":"Hello, World!"}
----




