[[ide-integration]]
== IDE integration

Spring AOT Maven and Gradle plugins need to be invoked before running your application and tests, it may potentially
require additional configuration.

=== Intellij IDEA

==== Maven

If build/run actions are not delegated to Maven (default), you may want to
https://www.jetbrains.com/help/idea/work-with-maven-goals.html#trigger_goal[configure triggers for Maven goals] as following.

In the Maven tool window, go to "Plugins" and map:

- Right click on `spring-aot:generate` then click on "After build"
- Right click on `spring-aot:test-generate` then  click on "Execute Run/Debug ..." then select your JUnit test configurations (may require to create them upfront)

If build/run actions are delegated to Maven, it should work out-of-the-box.

==== Gradle

TODO

=== Eclipse

==== Maven

Eclipse should configure out of the box the main generated sources, so the application should run out of the box with
the sources generated by the Spring AOT plugin.

But Eclipse does not support having the same classes in main and test generated sources, so test sources generation is
disabled by default and tests should run without the sources generated by the Spring AOT plugin in the IDE.

==== Gradle

TODO

=== VS code

TODO