include::attributes.adoc[]
= Spring Native documentation
Version {version} - Andy Clement; Sébastien Deleuze; Filip Hanik; Dave Syer; Esteban Ginez; Jay Bryant; Brian Clozel; Stéphane Nicoll; Josh Long

IMPORTANT: Spring Native is now superseded by Spring Boot 3 official native support, see https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html[the related reference documentation] for more details.

[[overview]]
== Overview

Spring Native provides support for compiling Spring applications to native executables using the https://www.graalvm.org[GraalVM] {graalvm-native-docs}/[native-image] compiler.

Compared to the Java Virtual Machine, native images can enable cheaper and more sustainable hosting for many types of workloads.
These include microservices, function workloads, well suited to containers, and https://kubernetes.io/[Kubernetes]

Using native image provides key advantages, such as instant startup, instant peak performance, and reduced memory consumption.

There are also some drawbacks and trade-offs that the GraalVM native project expect to improve on over time.
Building a native image is a heavy process that is slower than a regular application.
A native image has fewer runtime optimizations after warmup.
Finally, it is less mature than the JVM with some different behaviors.

The key differences between a regular JVM and this native image platform are:

* A static analysis of your application from the main entry point is performed at build time.
* The unused parts are removed at build time.
* Configuration is required for reflection, resources, and dynamic proxies.
* Classpath is fixed at build time.
* No class lazy loading: everything shipped in the executables will be loaded in memory on startup.
* Some code will run at build time.
* There are some https://www.graalvm.org/reference-manual/native-image/Limitations/[limitations] around some aspects of Java applications that are not fully supported.

The goal of this project is to incubate the support for Spring Native, an alternative to Spring JVM, and provide a native deployment option designed to be packaged in lightweight containers.
In practice, the target is to support your Spring applications, almost unmodified, on this new platform.

NOTE: This is work in progress, see the list of <<support,supported features>> for more details.

[[overview-modules]]
=== Modules

Spring Native is composed of the following modules:

* `spring-native`: runtime dependency required for running Spring Native, provides also <<native-hints>> API.
* `spring-native-configuration`: configuration hints for Spring classes used by Spring AOT plugins, including various Spring Boot auto-configurations.
* `spring-native-docs`: reference guide, in asciidoc format.
* `spring-native-tools`: tools used for reviewing image building configuration and output.
* `spring-aot`: AOT generation infrastructure common to Maven and Gradle plugins.
* `spring-aot-test`: Test-specific AOT generation infrastructure.
* `spring-aot-gradle-plugin`: Gradle plugin that invokes AOT generation.
* `spring-aot-maven-plugin`: Maven plugin that invokes AOT generation.
* `samples`: contains various samples that demonstrate features usage and are used as integration tests.

[[getting-started]]
== Getting started

There are two main ways to build a Spring Boot native application:

* Using <<getting-started-buildpacks, Spring Boot Buildpacks support>> to generate a lightweight container containing a native executable.
* Using <<getting-started-native-build-tools, the Native Build Tools>> to generate a native executable.

TIP: The easiest way to start a new native Spring Boot project is to go to https://start.spring.io, add the "Spring Native" dependency and generate the project.

include::getting-started-buildpacks.adoc[]

include::getting-started-native-build-tools.adoc[]

include::support.adoc[]

include::aot.adoc[]

include::native-hints.adoc[]

include::samples.adoc[]

include::native-image-options.adoc[]

include::tracing-agent.adoc[]

include::executable-jar-to-native.adoc[]

include::troubleshooting.adoc[]

include::how-to-contribute.adoc[]

[[contact-us]]
== Contact us

We would love to hear about your successes and failures (with minimal repro projects) through the {github-issues}[project issue tracker].
Before raising an issue, please check the <<troubleshooting,troubleshooting guide>>, which is full of information on pitfalls, common problems, and how to deal with them (through fixes and workarounds).

If you want to make a contribution here, see the <<how-to-contribute,how to contribute guide>>.
Please be aware this project is still incubating and, as such, some of these options and extension APIs are still evolving and may change before it is finally considered done.
