:toc: left
:toclevels: 4
:numbered:
:icons: font
:hide-uri-scheme:
:project-home: https://github.com/spring-projects-experimental/spring-native
:version: 0.9.0-SNAPSHOT
:repository: milestone
:boot-version: 2.4.3
:cloud-version: 2020.0.1
:graalvm-version: 21.0.0
= Spring Native for GraalVM documentation
Version {version} - Andy Clement; Sébastien Deleuze; Filip Hanik; Dave Syer; Esteban Ginez; Jay Bryant

== Overview

Spring Native provides support for compiling Spring applications to native executables using
https://www.graalvm.org[GraalVM] https://www.graalvm.org/reference-manual/native-image/[native-image] compiler.

Compared to the Java Virtual Machine, native images offers advantages like the following, enabling cheaper and more
sustainable hosting for certain kinds of workloads (microservices, functions) well suited for containers and https://kubernetes.io/[Kubernetes]:

- Instant startup
- Instant peak performance
- Reduced memory consumption

But also a few drawbacks that could be reduced in the future as GraalVM native evolves:

- Slower and heavy build
- Less runtime optimizations after warmup
- Less mature than the JVM with some different behaviors

The key differences between the regular JVM and this native image platform are:

- A static analysis of your application from the main entry point is performed at build time.
- The unused parts are removed at build time.
- Configuration is required for reflection, resources, and dynamic proxies.
- Classpath fixed at build time.
- No class lazy loading: everything shipped in the executables will be loaded in memory at startup.
- Some code will run at build time!
- There are some https://github.com/oracle/graal/blob/master/substratevm/Limitations.md[limitations].

The goal of this project is to incubate the support for Spring Native, an alternative to Spring JVM, in order to provide
a native deployment option designed to be packaged in lightweight containers. In practice, the target is
to support your Spring application (typically Spring Boot ones), unmodified, on this new platform.
Beware that we are not here yet, see the <<support>> documentation for more details.

=== Modules

The Spring Native for GraalVM project is composed of the following modules:

- `spring-native`: this module contains the runtime dependency required for running Spring native like the substitutions.
- `spring-native-configuration`: this module contains configuration hints for Spring classes, including various Spring Boot auto-configurations.
- `spring-native-samples`: contains various samples that demonstrate the feature usage and are used as integration tests.
- `spring-native-docs`: contains the asciidoc documentation sources.
- `spring-native-tools`: tools used for reviewing image building configuration and output.
- `spring-native-parent`: Maven parent pom with preconfigured dependency and plugin management.
- `spring-aot`: this module contains the AOT transformation infrastructure common to Maven and Gradle plugins.
- `spring-aot-maven-plugin`: this module contains the Maven plugin that invokes AOT transformations.

include::support.adoc[]

== Getting Started

There are two main ways to build Spring Boot native application:

- Using <<getting-started-buildpacks, Spring Boot Maven or Gradle Buildpacks support>> to generate a lightweight container containing a native executable
- Using <<getting-started-native-image, GraalVM native image Maven plugin support>> to generate a native executable

include::getting-started-buildpacks.adoc[]

include::getting-started-native-image.adoc[]

include::native-configuration.adoc[]

include::samples.adoc[]

include::options.adoc[]

include::tracing-agent.adoc[]

include::troubleshooting.adoc[]

include::how-to-contribute.adoc[]

== Contact us

We would love to hear about your successes and failures (with minimal repro projects) through the https://github.com/spring-projects-experimental/spring-native/issues[project issue tracker].
Before raising an issue, please check the <<troubleshooting,troubleshooting guide>>, which is full of information on pitfalls, common problems, and how to deal with them (through fixes and workarounds).

If you want to make a contribution here, see the <<how-to-contribute,how to contribute guide>>.
Please be aware this project is still incubating and, as such, some of these options and extension APIs are still evolving and may change before it is finally considered done.
