include::attributes.adoc[]
= Spring Native documentation
Version {version} - Andy Clement; Sébastien Deleuze; Filip Hanik; Dave Syer; Esteban Ginez; Jay Bryant; Brian Clozel

== Overview

Spring Native provides support for compiling Spring applications to native executables using the https://www.graalvm.org[GraalVM] {graalvm-native-docs}/[native-image] compiler.

Compared to the Java Virtual Machine, native images can enable cheaper and more sustainable hosting for many types of workload, for example microservices  and function workloads, well suited to containers and https://kubernetes.io/[Kubernetes].

Some key advantages of native images include:

- Instant startup
- Instant peak performance
- Reduced memory consumption

There are also some drawbacks/trade-offs that the GraalVM native project expect to improve on over time:

- Slower and heavy build
- Fewer runtime optimizations after warmup
- Less mature than the JVM with some different behaviors

The key differences between a regular JVM and this native image platform are:

- A static analysis of your application from the main entry point is performed at build time.
- The unused parts are removed at build time.
- Configuration is required for reflection, resources, and dynamic proxies.
- Classpath is fixed at build time.
- No class lazy loading: everything shipped in the executables will be loaded in memory at startup.
- Some code will run at build time!
- There are some https://github.com/oracle/graal/blob/master/substratevm/Limitations.md[limitations] around some aspects of Java applications that are not fully supported.

The goal of this project is to incubate the support for Spring Native, an alternative to Spring JVM, in order to provide a native deployment option designed to be packaged in lightweight containers.
In practice, the target is to support your Spring application (typically Spring Boot ones), almost unmodified, on this new platform.
Beware that we are not here yet, see the <<support>> documentation for more details.

=== Modules

The Spring Native for GraalVM project is composed of the following modules:

- `spring-native`: this module contains the runtime dependency required for running Spring native like the substitutions.
- `spring-native-configuration`: this module contains configuration hints for Spring classes, including various Spring Boot auto-configurations.
- `spring-native-docs`: contains the asciidoc documentation sources.
- `spring-native-tools`: tools used for reviewing image building configuration and output.
- `spring-aot`: this module contains the AOT transformation infrastructure common to Maven and Gradle plugins.
- `spring-aot-maven-plugin`: this module contains the Maven plugin that invokes AOT transformations.
- `spring-aot-gradle-plugin`: this module contains the Gradle plugin that invokes AOT transformations.
- `samples`: contains various samples that demonstrate the feature usage and are used as integration tests.

include::support.adoc[]

== Getting Started

There are two main ways to build a Spring Boot native application:

- Using <<getting-started-buildpacks, Spring Boot Maven or Gradle Buildpacks support>> to generate a lightweight container containing a native executable
- Using <<getting-started-native-image, GraalVM native image Maven plugin support>> to generate a native executable

include::getting-started-buildpacks.adoc[]

include::getting-started-native-image.adoc[]

include::spring-aot.adoc[]

include::native-hints.adoc[]

include::samples.adoc[]

include::native-image-options.adoc[]

include::tracing-agent.adoc[]

include::troubleshooting.adoc[]

include::how-to-contribute.adoc[]

== Contact us

We would love to hear about your successes and failures (with minimal repro projects) through the {github-issues}[project issue tracker].
Before raising an issue, please check the <<troubleshooting,troubleshooting guide>>, which is full of information on pitfalls, common problems, and how to deal with them (through fixes and workarounds).

If you want to make a contribution here, see the <<how-to-contribute,how to contribute guide>>.
Please be aware this project is still incubating and, as such, some of these options and extension APIs are still evolving and may change before it is finally considered done.
