[[native-hints]]
== Native hints

GraalVM native image supports configuration via static files that are automatically discovered when located in `META-INF/native-image`.
Those files can be {graalvm-native-docs}/BuildConfiguration/#configuration-file-format[native-image.properties], {graalvm-native-docs}/Reflection/[reflect-config.json], {graalvm-native-docs}/DynamicProxy/[proxy-config.json], or {graalvm-native-docs}/Resources/[resource-config.json].

Spring Native is generating such configuration files (that would sit alongside any user provided ones) via the Spring AOT build plugin.
However, there are situations where specifying additional native configuration is required:

* When reflection-based serialization is used in a programmatic API like `WebClient` with Jackson.
* To use a feature or library not yet supported by Spring Native.
* To specify native configuration related to your own application.

Here is the full list of what can be specified in a hint:

* `options` as defined in <<native-image-options, here>> that will be passed when executing `native-image`
* `jdkProxies` which list interfaces for which JDK proxy types are needed and should be built into the image.
* `aotProxies` which lists more complex proxy configurations where the proxy will extend a class.
* `types` which lists any reflective needs.
It should use class references but string names for classes are allowed if visibility (private classes) prevents a class reference.
If these are types that are accessed via JNI and should go into a `jni-config.json` file rather than `reflect-config.json` then ensure the access bit JNI is set when defining access.
* `serializables` which lists any serialization needs via a list of `@SerializationHint` annotations.
* `resources` which lists patterns that match resources (including .class files) that should be included in the image.
* `initialization` which lists classes/packages that should be explicitly initialized at either build-time or run-time.
There should not really be a trigger specified on hints included `initialization`.
* `imports` can be useful if two hints share a number of `@TypeHint`/`@JdkProxyHint`/etc in common.

Hints can be provided statically using an annotated model, or programmatically by implementing one of the callback interfaces.

=== Annotated Hints
Annotated hints can be put on any `@Configuration`-annotated class of your application, including `@SpringBootApplication`:

* `@TypeHint` for simple reflection hints
* `@NativeHint` is a container for `@TypeHint` and offer more options.

Let us take an example of an application using `WebClient` to deserialize a `Data` class with a `SuperHero` nested class using Jackson.
Such process requires reflective access to the class and can be configured as shown in the following example.

[source,java,subs="attributes,verbatim"]
----
@TypeHint(types = Data.class, typeNames = "com.example.webclient.Data$SuperHero")
@SpringBootApplication
public class SampleApplication {
	// ...
}
----

NOTE: Either the `Class` itself or its fully qualified name can be provided.
For nested classes, the `$` separator should be used.

Spring Native itself provides hints for a number of libraries so that they work out-of-the-box.
Hints classes should implement `NativeConfiguration` and be registered in `META-INF/spring.factories`.
If you need some concrete example of hints, you can {github-tree}/spring-native-configuration/src/main/java[browse ours].

=== Programmatic Hints
Spring Native provides a {github-tree}/spring-aot/src/main/java/org/springframework/aot/context/bootstrap/generator/infrastructure/nativex/NativeConfigurationRegistry.java[programmatic registry] which exposes a high-level API for all hints.

Three callbacks are provided:

. `BeanFactoryNativeConfigurationProcessor` provides the `BeanFactory` so that it can be introspected for matching beans.
. `BeanNativeConfigurationProcessor` provides a `BeanInstanceDescriptor` for each bean.
. `NativeConfiguration` typically used for hints not related to beans or `BeanFactory`.

WARNING: Those types are available via the `org.springframework.experimental:spring-aot` dependency which should not be in the runtime classpath, so you should typically use `<scope>provided</scope>` with Maven or `compileOnly` configuration with Gradle.

`BeanFactoryNativeConfigurationProcessor` should be used when a particular aspect of matching beans is requested.
A typical example is automatically processing beans having a certain annotation.
`BeanNativeConfigurationProcessor`, however, is more suited when processing all beans, regardless of their nature.

Let us take an example of an application that has `@CustomClient`-annotated beans.
Such bean uses a `WebClient` internally and the return types of public methods are DTO used for transfer.
As we have seen in the previous example, reflection access is required for those.
The sample below registers those hints automatically:

[source,java,subs="attributes,verbatim"]
----
class CustomClientNativeConfigurationProcessor implements BeanFactoryNativeConfigurationProcessor {

    void process(ConfigurableListableBeanFactory beanFactory, NativeConfigurationRegistry registry) {
        String[] beanNames = beanFactory.getBeanNamesForAnnotation(CustomClient.class);
        for (String beanName : beanNames) {
            Class<?> clientType = beanFactory.getMergedBeanDefinition(beanName).getResolvableType().toClass();
            ReflectionUtils.doWithMethods(clientType, registerNativeConfiguration(registry), publicDtoMethods());
        }
    }

    private MethodCallback registerNativeConfiguration(NativeConfigurationRegistry registry) {
        return (method) -> {
            registry.reflection().forType(method.getReturnType())
                    .withAccess(TypeAccess.DECLARED_CONSTRUCTORS, TypeAccess.DECLARED_METHODS);
        };
    }

	private MethodFilter publicDtoMethods() {
        return (method) -> Modifier.isPublic(method.getModifiers())
                && method.getReturnType() != Void.class;
    }
}
----

Two important bits are worth mentioning:

* The `BeanFactory` parameter is the prepared bean factory and could technically create instances.
To prevent that from happening we are retrieving the bean definition, not the bean itself.
* `getMergedBeanDefinition` is preferred as it contains the full resolution.

Custom implementations, such as the `CustomClientNativeConfigurationProcessor` above, should be registered in `META-INF/spring.factories`.

=== Manual Hints
Annotations and programmatic hints are automatically invoked as part of the build process if the <<build-setup,AOT build plugin>> is configured.
It is also possible to provide directly GraalVM native configuration files if you prefer to do so, but annotation based configuration is usually easier to write and to maintain thanks to auto-completion and compilation type checks.
Programmatic hints are easily testable as well.


