[[native-configuration]]
== Native configuration

GraalVM native image provides out-of-the-box configuration with static files that can be discovered when located
in `META-INF/native-image` in your application classpath. Those files can be
https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/#configuration-file-format[native-image.properties],
https://www.graalvm.org/reference-manual/native-image/Reflection/[reflect-config.json],
https://www.graalvm.org/reference-manual/native-image/DynamicProxy/[proxy-config.json] or
https://www.graalvm.org/reference-manual/native-image/Resources/[resource-config.json] for example.

=== Native configuration with `@NativeHint` ===

There are cases when specifying native configuration is required:
- When reflection-based serialization is used in a programmatic API like `WebClient` with Jackson
- When you try to use a feature or library not yet supported by Spring Native
- When you are want to specify native configuration related to your own application.

For those, you can annotate classes already annotated with `@Configuration` or `@SpringBootApplication` with
`@NativeHint`.

For example, an application using `WebClient` to deserialize a `Data` class with a `SuperHero` nested class
should be configured as below (see the Javadoc for more details):

====
[source,java,subs="attributes,verbatim"]
----
@NativeHint(types = @TypeHint(types = Data.class, typeNames = "com.example.webclient.Data$SuperHero"))
@SpringBootApplication
public class WebClientApplication {
 // ...
}
----
====

In fact, Spring Native itself is configuring most of your application with such annotations provided out of the box,
you can https://github.com/spring-projects-experimental/spring-native/tree/master/spring-native-configuration/src/main/java[browse them]
in order to see some concrete example of hints.

Those hints will be taken in account during the compilation and transformed to generated native configuration by the
Spring AOT plugin. It is of course also possible to provide directly GraalVM native configuration files if you prefer
to do so, but annotation based configuration is usually easier to write and to maintain thanks to autocompletion and
compilation checks.

Here is the full list of what can be specified in a hint:

* `proxies` which list proxies for which types are needed and should be built into the image.

* `types` which lists any reflective needs. It should use class references but string names for classes are allowed if visibility (private classes) prevents a class reference.

* `resources` which lists patterns that match resources (including .class files) that should be included in the image.

* `initialization` which lists classes/packages that should be explicitly initialized at either build-time or run-time. There should not really be a trigger specified on hints included `initialization`.

* `imports` can be useful if two hints share a number of @TypeHint/@ProxyHint/etc in common. For example reactive-web and webmvc may expose a lot of common infrastructure. Rather than duplicate those in two places, those info annotations (TypeInfo/ProxyInfo/etc) can all be placed on a separate type and then `imports` can reference that type to pull them into a particular `NativeHint`.


For details and more dynamic ways to provide native configuration, see <<how-to-contribute>> section.