[[native-image-options]]
== Native image options

GraalVM `native-image` options are documented {graalvm-native-docs}/Options/[here].
Spring Native is enabling automatically some of those, and some others especially useful are documented here as well.

They can be specified using the `BP_NATIVE_IMAGE_BUILD_ARGUMENTS` environment variable in Spring Boot plugin if you are using {spring-boot-docs}/html/spring-boot-features.html#boot-features-container-images-buildpacks[Buildpacks support] or using the `<buildArgs></buildArgs>` configuration element if you are using `native-image-maven-plugin`.

[[native-image-options-default]]
=== Options enabled by default

These options are enabled by default when using Spring Native, since they are mandatory to make a Spring application work when compiled as GraalVM native images.

* `--allow-incomplete-classpath` allows image building with an incomplete class path and reports type resolution errors at run time when they are accessed the first time, instead of during image building.
* `--report-unsupported-elements-at-runtime` reports usage of unsupported methods and fields at run time when they are accessed the first time, instead of as an error during image building.
* `--no-fallback` enforces native image only runtime and disable fallback on regular JVM.
* `--install-exit-handlers` allows to react to a shutdown request from Docker.

[[native-image-options-useful]]
=== Useful options

* `--verbose` makes image building output more verbose.
* `-H:+ReportExceptionStackTraces` provides more detail should something go wrong.
* `--initialize-at-build-time` initializes classes by default at build time without any class or package being specified.
This option is currently (hopefully, temporarily) required for Netty-based applications but is not recommended for other applications, since it can trigger compatibility issues, especially regarding logging and static fields.
See {github-issues}/8[this issue] for more details.
You can use it with specific classes or package specified if needed.
* `-H:+PrintAnalysisCallTree` helps to find what classes, methods, and fields are used and why.
* `-H:Log=registerResource:3` prints the resources included in the native image.
You can find more details in GraalVM https://github.com/oracle/graal/blob/master/substratevm/Reports.md[reports documentation].
* `-H:ReportAnalysisForbiddenType=com.example.Foo` helps to find why the specified class is included in the native image.
* `--trace-class-initialization` provides a comma-separated list of fully-qualified class names that a class initialization is traced for.
* `--trace-object-instantiation` provides a comma-separated list of fully-qualified class names that an object instantiation is traced for.
* `--enable-https` enables HTTPS support (common need when using `WebClient` or `RestTemplate` for example).

[[native-image-options-unsupported]]
=== Unsupported options

* `--initialize-at-build-time` without class or package specified is not supported since Spring Native for GraalVM is designed to work with runtime class initialization by default (a selected set of classes are enabled at buildtime).

