[[options]]
== Options

=== Spring Native options

Spring Native options are configured at `spring-aop-maven-plugin` or `spring-aop-gradle-plugin` configuration level.

* `mode` switches how much configuration the feature actually provides to the native image compiler:
** `native` (activated by default) provides resource, initialization, proxy and reflection (using auto-configuration hints) configuration for native images as well as substitutions.
** `native-init` (manually activated) should be used if only wishing to provide initialization configuration and substitutions.
** `native-agent` (manually activated) is using the configuration generated by the tracing agent as a basis and also provides additional hints for components like controllers, etc.

* `debugVerify` enables verification debug when set to `true`.

* `removeXmlSupport` restores Spring XML support when set to `false` to optimize the footprint (removed by default).

* `removeSpelSupport` removes Spring SpEL support when set to `true` to optimize the footprint

* `removeYamlSupport` removes Spring Boot Yaml support when set to `true` to optimize the footprint.

* `removeJmxSupport` restores Spring Boot JMX support when set to `false` to optimize the footprint (removed by default).

* `verify` switches off the verifier mode when set to `false` (enabled by default). See the <<support#_limitations>> section for more details on this experimental option.

* `removeUnusedConfig` disables removal of unused configurations  when set to `false`.

* `buildTimePropertiesChecks` switches on build time evaluation of some configuration conditions related to properties. It must include at least an initial setting of `default-include-all` or `default-exclude-all` and that may be followed
by a comma separated list of prefixes to explicitly include or exclude (for example `default-include-all,!spring.dont.include.these.,!or.these` or `default-exclude-all,spring.include.this.one.though.,and.this.one`). When considering a property the
longest matching prefix in this setting will apply (in cases where a property matches multiple prefixes).

* `buildTimePropertiesMatchIfMissing` set to `false` means for any properties specifying `matchIfMissing=true` that will be overridden and not respected. This does flip the application into a mode where it needs to be much more explicit
about specifying properties that activate configurations. (This is a work in dev option really for experimenting with image size vs explicit property trade offs).

=== GraalVM options

GraalVM offers options that are enabled by default and others that are not enabled by default (some of which are recommended, though).

==== Options enabled by default

These options are enabled by default when using `spring-native`, since they are mandatory to make a Spring application work when compiled as GraalVM native images.

* `--allow-incomplete-classpath` allows image building with an incomplete class path and reports type resolution errors at run time when they are accessed the first time, instead of during image building.

* `--report-unsupported-elements-at-runtime` reports usage of unsupported methods and fields at run time when they are accessed the first time, instead of as an error during image building.

* `--no-fallback` enforces native image only runtime and disable fallback on regular JVM.

* `--no-server` means do not use the image-build server which can be sometimes unreliable, see https://github.com/oracle/graal/issues/1952[graal#1952] for more details.

* `--install-exit-handlers` allows to react to a shutdown request from Docker.

* `-H:+InlineBeforeAnalysis` enables inlining before analysis in order to allow utility methods returning a constant to be taken in account for code removal for example.

Notice that XML and JMX support is disable by default, see options bellow to enable them if needed.

==== Options recommended by default

* `--verbose` makes image building output more verbose.

* `-H:+ReportExceptionStackTraces` provides more detail should something go wrong.

==== Other options

* `--initialize-at-build-time` initializes classes by default at build time without any class or package being specified.
This option is currently (hopefully, temporarily) required for Netty-based applications but is not recommended for other applications, since it can trigger compatibility issues, especially regarding logging and static fields.
See {project-home}/issues/8[this issue] for more details.
You can use it with specific classes or package specified if needed.

* `-H:+PrintAnalysisCallTree` helps to find what classes, methods, and fields are used and why.
You can find more details in GraalVM https://github.com/oracle/graal/blob/master/substratevm/Reports.md[reports documentation].

* `-H:ReportAnalysisForbiddenType=com.example.Foo` helps to find why the specified class is included in the native image.

* `-H:+TraceClassInitialization` provides useful information to debug class initialization issues.

* `--enable-all-security-services` required for crypto and some security services.

* `--enable-http` enables HTTP support.

* `--enable-https` enables HTTPS support.

=== Unsupported options

* `--initialize-at-build-time` without class or package specified is not supported since Spring Native for GraalVM is designed to work with runtime class initialization by default (a selected set of classes are enabled at buildtime).

