[[options]]
== Options

You can tweak the behavior of GraalVM native by setting options.
These are passed to `native-image` as command line parameters, in a `META-INF/native-image/native-image.properties` file with an `Args` key or through the `<buildArgs>..</buildArgs>` block when invoking with Maven.

=== GraalVM options

GraalVM offers options that are enabled by default and others that are not enabled by default (some of which are recommended, though).

==== Options enabled by default

These options are enabled by default when using `spring-native`, since they are mandatory to make a Spring application work when compiled as GraalVM native images.

* `--allow-incomplete-classpath` allows image building with an incomplete class path and reports type resolution errors at run time when they are accessed the first time, instead of during image building.

* `--report-unsupported-elements-at-runtime` reports usage of unsupported methods and fields at run time when they are accessed the first time, instead of as an error during image building.

* `--no-fallback` enforces native image only runtime and disable fallback on regular JVM.

* `--no-server` means do not use the image-build server which can be sometimes unreliable, see https://github.com/oracle/graal/issues/1952[graal#1952] for more details.

* `--install-exit-handlers` allows to react to a shutdown request from Docker.

* `-H:+InlineBeforeAnalysis` enables inlining before analysis in order to allow utility methods returning a constant to be taken in account for code removal for example.

Notice that XML and JMX support is disable by default, see options bellow to enable them if needed.

==== Options recommended by default

* `--verbose` makes image building output more verbose.

* `-H:+ReportExceptionStackTraces` provides more detail should something go wrong.

==== Other options

* `--initialize-at-build-time` initializes classes by default at build time without any class or package being specified.
This option is currently (hopefully, temporarily) required for Netty-based applications but is not recommended for other applications, since it can trigger compatibility issues, especially regarding logging and static fields.
See {project-home}/issues/8[this issue] for more details.
You can use it with specific classes or package specified if needed.

* `-H:+PrintAnalysisCallTree` helps to find what classes, methods, and fields are used and why.
You can find more details in GraalVM https://github.com/oracle/graal/blob/master/substratevm/Reports.md[reports documentation].

* `-H:ReportAnalysisForbiddenType=com.example.Foo` helps to find why the specified class is included in the native image.

* `-H:+TraceClassInitialization` provides useful information to debug class initialization issues.

=== Spring Framework/Boot options

* `-Dspring.spel.ignore=true` removes SpEL support, enabling faster compilation and smaller executables.

* `-Dspring.xml.ignore=false` restores XML support (removed by default).

=== Spring Native options

The current feature options are as follows:

* `-Dspring.native.mode=reflection|init|agent` switches how much configuration the feature actually provides
to native-image.

- `reflection` (activated by default) provides resource, initialization, proxy and reflection (using auto-configuration hints) configuration for native images as well as substitutions.
- `init` (manually activated) should be used if only wishing to provide initialization configuration and substitutions.
- `agent` (experimental, activated when agent-generated config is present) is using the configuration generated by the tracing agent as a basis and also provides additional hints for components like controllers, etc.

* `-Dspring.native.verbose=true` outputs lots of information about the feature behavior as it processes auto-configuration and chooses which to include.

* `-Dspring.native.remove-jmx-support=false` restores Spring Boot JMX support (removed by default).

* `-Dspring.native.remove-yaml-support=true` removes Spring Boot Yaml support, enabling faster compilation and smaller executables.

* `-Dspring.native.dump-config=/tmp/dump.txt` dumps the configuration to the specified file.

* `-Dspring.native.verify=false` switches off the verifier mode (on by default).
See the <<support#_limitations>> section for more details on this experimental option.

* `-Dspring.native.missing-selector-hints=warning` switches the feature from a hard error for missing hints to a warning.
See the <<troubleshooting>> section for more details on this.

* `-Dspring.native.remove-unused-autoconfig=false` disables removal of unused configurations.

* `-Dspring.native.fail-on-version-check=false` disables failure on Spring Boot version check.

* `-Dspring.native.factories.no-actuator-metrics=true` disables inclusion of metrics related actuator infrastructure when importing the actuator starter. Large reduction in memory usage with this turned on (obviously only usable if the application does not require that infrastructure).

* `-Dspring.native.build-time-properties-checks=` switches on build time evaluation of some configuration conditions related to properties. It must include at least an initial setting of `default-include-all` or `default-exclude-all` and that may be followed
by a comma separated list of prefixes to explicitly include or exclude (for example `=default-include-all,!spring.dont.include.these.,!or.these` or `=default-exclude-all,spring.include.this.one.though.,and.this.one`). When considering a property the
longest matching prefix in this setting will apply (in cases where a property matches multiple prefixes).

* `-Dspring.native.build-time-properties-match-if-missing=false` means for any properties specifying `matchIfMissing=true` that will be overridden and not respected. This does flip the application into a mode where it needs to be much more explicit
about specifying properties that activate configurations. (This is a work in dev option really for experimenting with image size vs explicit property trade offs).

=== Other options

* `--enable-all-security-services` required for crypto and some security services.

* `--enable-http` enables HTTP support.

* `--enable-https` enables HTTPS support.

=== Unsupported options

* `--initialize-at-build-time` without class or package specified is not supported since Spring Native for GraalVM is designed to work with runtime class initialization by default (a selected set of classes are enabled at buildtime).

