[[spring-aot]]
== Spring AOT

Spring AOT build plugins are designed to generate and compile sources by taking advantage of the context of your application (classpath, configuration) in order to improve native image compatibility and footprint.
It is invoked before running your application and tests, and may potentially require additional IDE configuration.

[[spring-aot-maven]]
=== Maven

The plugin should be declared as following:

[source,xml,subs="attributes,verbatim",role="primary"]
.Maven
----
<build>
    <plugins>
        <!-- ... -->
        <plugin>
            <groupId>org.springframework.experimental</groupId>
            <artifactId>spring-aot-maven-plugin</artifactId>
            <version>{version}</version>
            <executions>
                <execution>
                    <id>test-generate</id>
                    <goals>
                        <goal>test-generate</goal>
                    </goals>
                </execution>
                <execution>
                    <id>generate</id>
                    <goals>
                        <goal>generate</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
----

WARNING: With Maven, the `org.springframework.experimental:spring-native` dependency is mandatory, so make sure to add it to `<dependencies></dependencies>`.

Maven goals `spring-aot:generate` (`process-test-classes` phase) and `spring-aot:test-generate` (`prepare-package` phase) are automatically invoked in the Maven lifecycle when using the `mvn verify` or `mvn package` commands.
The `spring-aot:*` goals are not meant to be called by themselves since they rely on other parts of the lifecycle.
Sources are generated in `target/generated-sources/spring-aot/` and test sources in `target/generated-test-sources/spring-aot/`.

NOTE: Because of a temporary limitation of the AOT plugin, developers need to trigger the `package` phase if they wish to run the application with the Spring Boot Maven plugin:
please use `mvn package spring-boot:run`.

Configuration can be performed if needed within the `<configuration>` element, for example to remove SpEL support at build-time if your application does not use it in order to optimize the footprint:

[source,xml,subs="attributes,verbatim"]
----
<configuration>
    <removeSpelSupport>true</removeSpelSupport>
</configuration>
----

See <<spring-aot-configuration>> for a list of the configuration options available.

==== Intellij IDEA

If build/run actions are not delegated to Maven (default), you may want to https://www.jetbrains.com/help/idea/work-with-maven-goals.html#trigger_goal[configure triggers for Maven goals] as following.

In the Maven tool window, go to "Plugins" and map:

- Right click on `spring-aot:generate` then click on "After build".
- Add the JUnit configuration (or just try to run a firs time your tests) and then right click on `spring-aot:test-generate` then  click on "Execute Run/Debug ..." then select your JUnit test configurations.

If build/run actions are delegated to Maven, it should work out-of-the-box.

==== Eclipse and VSCode

Eclipse with m2e (Maven) or Buildship (Gradle) should configure out of the box the main generated sources, so the application should run out of the box with the sources generated by the Spring AOT plugin.

But Eclipse does not support having the same classes in main and test generated sources, so test sources generation is disabled by default and tests should run without the sources generated by the Spring AOT plugin in the IDE.

VSCode uses the same build tooling as Eclipse, so it should work the same.

[[spring-aot-gradle]]
=== Gradle

You can configure the Gradle Spring AOT plugin by declaring first the plugin repositories in your `settings.gradle(.kts)` file:

[source,groovy,subs="attributes,verbatim",role="primary"]
.Gradle Groovy
----
pluginManagement {
    repositories {
        // ...
        maven { url 'https://repo.spring.io/{spring-native-repo}' }
    }
}
----
[source,Kotlin,subs="attributes,verbatim",role="secondary"]
.Gradle Kotlin
----
pluginManagement {
    repositories {
        // ...
        maven { url = uri("https://repo.spring.io/{spring-native-repo}") }
    }
}
----

[source,groovy,subs="attributes,verbatim",role="primary"]
.Gradle Groovy
----
plugins {
    // ...
    id 'org.springframework.experimental.aot' version '{version}'
}
----
[source,Kotlin,subs="attributes,verbatim",role="secondary"]
.Gradle Kotlin
----
plugins {
    // ...
    id("org.springframework.experimental.aot") version "{version}"
}
----

The plugin creates two `SourceSets` for testing and running the application: "aot" and "aotTest".
The resulting classes and resources are automatically added to the runtime classpath of the application when running the `test`, `bootRun` and `bootJar` tasks.

Sources are generated in `build/generated/sources/aot/`, `build/generated/resources/aot/` and test sources in `build/generated/sources/aotTest/`, `build/generated/resources/aotTest/`.

Configuration can be performed if needed using the `springAot` DSL extension, for example to remove SpEL support at build-time if your application does not use it in order to optimize the footprint:

[source,groovy,subs="attributes,verbatim",role="primary"]
.Gradle Groovy
----
springAot {
	removeSpelSupport = true
}
----
[source,Kotlin,subs="attributes,verbatim",role="secondary"]
.Gradle Kotlin
----
springAot {
	removeSpelSupport.set(true)
}
----

Here is a complete code sample showing all the default values and how to set them:

[source,groovy,subs="attributes,verbatim",role="primary"]
.Gradle Groovy
----
import org.springframework.aot.gradle.dsl.AotMode

// ...

springAot {
	mode = AotMode.NATIVE
	debugVerify = false
	removeXmlSupport = true
	removeSpelSupport = false
	removeYamlSupport = false
	removeJmxSupport = true
	verify = true
	removeUnusedConfig = true
	failOnMissingSelectorHint = true
	buildTimePropertiesMatchIfMissing = true
	buildTimePropertiesChecks = ["default-include-all","!spring.dont.include.these.","!or.these"]
}
----
[source,Kotlin,subs="attributes,verbatim",role="secondary"]
.Gradle Kotlin
----
import org.springframework.aot.gradle.dsl.AotMode

// ...

springAot {
	mode.set(AotMode.NATIVE)
	debugVerify.set(false)
	removeXmlSupport.set(true)
	removeSpelSupport.set(false)
	removeYamlSupport.set(false)
	removeJmxSupport.set(true)
	verify.set(true)
	removeUnusedConfig.set(true)
	failOnMissingSelectorHint.set(true)
	buildTimePropertiesMatchIfMissing.set(true)
	buildTimePropertiesChecks.set(arrayOf("default-include-all","!spring.dont.include.these.","!or.these"))
}
----

NOTE: The non-idomatic `property.set(...)` syntax in the Gradle Kotlin DSL is due to https://github.com/gradle/gradle/issues/9268[gradle#9268], feel free to vote for this issue.

See <<spring-aot-configuration>> for more details on the configuration options.

==== Intellij IDEA

For now, you should run or debug your application in Intellij IDEA by going to the Gradle tool windows -> Tasks -> application and right click on bootRun, then choose one of the Run or Debug entries.

[[spring-aot-configuration]]
=== Configuring Spring AOT

* `mode` switches how much configuration the plugin actually provides to the native image compiler:
** `native` (default) provides resource, initialization, proxy and reflection (using auto-configuration hints) configuration for native images as well as substitutions.
** `native-init` should be used if only wishing to provide initialization configuration and substitutions.
** `native-agent` is using the configuration generated by the tracing agent as a basis and also provides additional hints for components like controllers, etc.

* *`removeXmlSupport` is set to `true` by default to optimize the footprint, setting it to `false` restores Spring XML support (XML converters, codecs and XML application context support).*

* `removeSpelSupport` is set to `false` by default, setting it to `true` removes Spring SpEL support to optimize the footprint (should be used only on applications not requiring SpEL).

* `removeYamlSupport` is set to `false` by default, setting it to `true` removes Spring Boot Yaml support to optimize the footprint.

* *`removeJmxSupport` is set to `true` by default to optimize the footprint, setting it to `false` restores Spring Boot JMX support.*

* `verify` is set to `true` by default and perform some automated verification to ensure your application is native compliant, setting it to `false` switches off the verifications.

* `debugVerify` is set to `false` by default and enables verification debug when set to `true`.

* `removeUnusedConfig` is set to `true` by default, setting it to `false` disables the removal of unused configurations.

* `failOnMissingSelectorHint` is set to `true` by default and throw an error if no hint is provided for an active selector, setting it to `false` switches the plugin from a hard error to a warning. See the Troubleshooting section for more details on this.

* [Experimental] `buildTimePropertiesMatchIfMissing` is set to `true` by default. Setting it to `false` means for any properties specifying `matchIfMissing=true` that will be overridden and not respected. This does flip the application into a mode where it needs to be much more explicit
about specifying properties that activate configurations. (This is a work-in-progress option really for experimenting with image size vs explicit property trade offs).

* [Experimental] `buildTimePropertiesChecks` (experimental) switches on build time evaluation of some configuration conditions related to properties. It must include at least an initial setting of `default-include-all` or `default-exclude-all` and that may be followed
by a comma separated list of prefixes to explicitly include or exclude (for example `default-include-all,!spring.dont.include.these.,!or.these` or `default-exclude-all,spring.include.this.one.though.,and.this.one`). When considering a property the
longest matching prefix in this setting will apply (in cases where a property matches multiple prefixes).

