[[spring-aot]]
== Spring AOT
Spring AOT (Ahead-of-Time) inspects an application at build-time and generates an optimized version of it.
Based on your `@SpringBootApplication`-annotated main class, the AOT engine generates a persistent view of the beans that are going to be contributed at runtime in a way that bean instantiation is as straightforward as possible.
Additional post-processing of the factory is possible using callbacks.
For instance, these are used to generate the necessary <<native-hints,reflection configuration>> that GraalVM needs to initialize the context in a native image.

The engine goes through the following phases:

. Prepare the underlying `BeanFactory` so that the relevant bean definitions are available.
This typically includes bean definitions model parsing (such as `@Configuration`-annotated classes) as well as any additional post-processing of the bean factory.
. Code generation based on the prepared `BeanFactory`.
Each bean definition is handled one by one and the necessary code to instantiate the bean and its necessary runtime semantics (such as primary flag) is generated.
. Additional processing of the bean factory used to optimize the runtime.

[[spring-aot-bean-factory-preparation]]
=== BeanFactory Preparation
As the `BeanFactory` is fully prepared at build-time, conditions are also evaluated.
This has an important difference compared to what a regular Spring Boot application does at runtime.
For instance, if you want to opt-in or opt-out for certain features, you need to configure the environment used at build time to do so.

While certain properties like passwords or url can be changed once the application has been prepared, properties that affect, typically, auto-configurations should be set at build-time.

[NOTE]
====
Conditions on the runtime environment, such as enabling features based on your chosen cloud platform, will no longer run at runtime.
====

Low-level framework callbacks, such as `BeanDefinitionRegistryPostProcessor` are invoked at build-time to create any additional bean definitions.
To prevent such a callback to be invoked at runtime again, it is not registered as bean, unless it does not have an `infrastructure` role.

[[spring-aot-code-generation]]
=== Code Generation
Based on a bean name and a merged `RootBeanDefinition`, the engine identifies a suitable `BeanRegistrationWriter` that is responsible to write the necessary code to instantiate the bean at runtime.

It is not expected that projects have to define their own writers, but this could happen for corner-cases.
Writers are identified via implementations of `BeanRegistrationWriterSupplier`, registered in `META-INF/spring.factories`.
Suppliers are ordered with a first-win approach, and a {github-tree}/spring-aot/src/main/java/org/springframework/aot/context/bootstrap/generator/bean/DefaultBeanRegistrationWriterSupplier.java[default implementation] with lowest precedence that handles most use cases is provided.

NOTE: Explicit care is required if a bean requires privileged access in more than one package.
This happens typically if the bean use `protected` access and extends from another class in a different package that does the same.
As a rule of thumb, make sure that each custom bean of yours can be instantiated in a test in a usable form.

[[spring-aot-additional-processing]]
=== Additional Processing
Additional processing of the `BeanFactory` currently only scans for `@EventListener`-annotated methods, but future versions may provide additional implementations.

More core to GraalVM support is the generation of an optimized set of native configuration based on the actual beans of the application, as covered by the next section.
