[[spring-aot]]
== Spring AOT

Spring AOT build plugins are designed to generate and compile sources by taking advantage of the context of your application
(classpath, configuration) in order to improve native image compatibility and footprint. It is invoked before
running your application and tests, and may potentially require additional IDE configuration.

=== Maven

Maven goals `spring-aot:generate` (`process-test-classes` phase) and `spring-aot:test-generate` (`prepare-package` phase)
should be invoked automatically in the Maven lifecycle when using the `mvn` command.

Sources are generated in
`target/generated-sources/spring-aot/src/main/resources/META-INF/native-image/org.springframework.aot/spring-aot`
and test sources in
`target/generated-test-sources/spring-aot/src/main/resources/META-INF/native-image/org.springframework.aot/spring-aot`.

==== Intellij IDEA

If build/run actions are not delegated to Maven (default), you may want to
https://www.jetbrains.com/help/idea/work-with-maven-goals.html#trigger_goal[configure triggers for Maven goals] as following.

In the Maven tool window, go to "Plugins" and map:

- Right click on `spring-aot:generate` then click on "After build".
- Add the JUnit configuration (or just try to run a firs time your tests) and then right click on `spring-aot:test-generate` then  click on "Execute Run/Debug ..." then select your JUnit test configurations.

If build/run actions are delegated to Maven, it should work out-of-the-box.

==== Eclipse

Eclipse should configure out of the box the main generated sources, so the application should run out of the box with
the sources generated by the Spring AOT plugin.

But Eclipse does not support having the same classes in main and test generated sources, so test sources generation is
disabled by default and tests should run without the sources generated by the Spring AOT plugin in the IDE.

==== VS code

TODO


=== Gradle

TODO
