[[support]]
== Support

This section defines the GraalVM version, languages and dependencies that have been validated against Spring Native {version},
which provides beta support on the scope defined in this section. You can try it on your projects if they are using those
supported dependencies, and https://github.com/spring-projects-experimental/spring-native/issues[raise bugs] or
https://github.com/spring-projects-experimental/spring-native/pulls[contribute pull requests] if something goes wrong.

Beta support also means that breaking changes will happen, but a migration path will be provided and documented.

[[support-graalvm]]
=== GraalVM

GraalVM version {graalvm-version} is supported, see the related https://www.graalvm.org/release-notes/[release notes].
GraalVM issues impacting the Spring ecosystem are identified on their issue tracker using https://github.com/oracle/graal/labels/spring[the `spring` label].

[[support-language]]
=== Language

Java 8, Java 11, and Kotlin 1.3+ are supported.

NOTE: Java 11 native images are currently impacted by a transient footprint issue that may lead (or not) to bigger images due to https://github.com/oracle/graal/issues/3163[oracle/graal#3163].

Kotlin Coroutines are supported but require additional reflection entries due to how Coroutines generates bytecode with an `Object` return type.

[[support-feature-flags]]
=== Feature flags

Some features like HTTPS may require some additional flags, check <<native-image-options>> for more details.
When it recognizes certain usage scenarios, Spring Native tries to set required flags automatically.

[[support-spring-boot]]
=== Spring Boot

IMPORTANT: Spring Native {version} is designed to be used with Spring Boot {spring-boot-version}. A new release of Spring Native will happen for each patch release of the latest Spring Boot 2.x minor version in order to ensure support and compatibility.

The following starters are supported, the group ID is `org.springframework.boot` unless specified otherwise.

* `spring-boot-starter-actuator`: WebMvc and WebFlux are supported, as well as metrics and tracing infrastructure.
Beware that actuators significantly increase the footprint, this will be optimized in a future release.
* `spring-boot-starter-data-elasticsearch`
* `spring-boot-starter-data-jdbc`
* `spring-boot-starter-data-jpa`
** You need to configure https://docs.jboss.org/hibernate/orm/5.4/topical/html_single/bytecode/BytecodeEnhancement.html#_build_time_enhancement[Hibernate build-time bytecode enhancement]
** `hibernate.bytecode.provider=none` is automatically set
* `spring-boot-starter-data-mongodb`
* `spring-boot-starter-data-neo4j`
* `spring-boot-starter-data-r2dbc`
* `spring-boot-starter-data-redis`
* `spring-boot-starter-jdbc`
* `spring-boot-starter-integration`
* `spring-boot-starter-logging`
** Logback is supported, but https://github.com/spring-projects-experimental/spring-native/issues/625[not configuration with `logback.xml`] so please configure it with `application.properties` or `application.yml` for now, or use <<logback-workaround, this workaround>> to configure it programmatically.
** Log4j2 is not supported yet, see https://github.com/spring-projects-experimental/spring-native/issues/115[#115].
* `spring-boot-starter-mail`
* `spring-boot-starter-thymeleaf`
* `spring-boot-starter-rsocket`
* `spring-boot-starter-validation`
* `spring-boot-starter-security`: WebMvc and WebFlux form login, HTTP basic authentication and OAuth 2.0 are supported.
RSocket security is also supported.
* `spring-boot-starter-oauth2-resource-server`: WebMvc and WebFlux are supported.
* `spring-boot-starter-oauth2-client`: WebMvc and WebFlux are supported.
* `spring-boot-starter-webflux`:
** For Web support, only Reactor Netty is supported for now.
** For WebSocket support, Tomcat, Jetty 9, Undertow and Reactor Netty are supported. Jetty 10 is not supported.
* `spring-boot-starter-web`:
** Only Tomcat is supported for now.
** `--enable-https` flag is required for HTTPS support.
** `org.apache.tomcat.experimental:tomcat-embed-programmatic` dependency can be used instead of `tomcat-embed-core` and `tomcat-embed-websocket` ones for optimized footprint.
* `spring-boot-starter-websocket`
* `com.wavefront:wavefront-spring-boot-starter`
* `spring-boot-starter-quartz`: supports the http://www.quartz-scheduler.org/[Quartz Job Scheduling] engine. It adds types required by Quartz, and automatically registers any `Job` subclasses for reflection.
* `spring-boot-starter-test`
** Additional native hints could be required for now, for example for `@AutoConfigureXxx` annotations. This limitation will be removed in upcoming versions.
** Libraries generating bytecode at runtime like Mockito are not supported.
** The testing support is based on https://github.com/graalvm/native-build-tools.

[[support-spring-cloud]]
=== Spring Cloud

IMPORTANT: Spring Native {version} is designed to be used with Spring Cloud {spring-cloud-version}.

Group ID is `org.springframework.cloud`.

NOTE: When using Spring Native, `spring.cloud.refresh.enabled` is set to `false` for compatibility and footprint reasons. `spring.sleuth.async.enabled` is also set to `false` since this feature leads to too much proxies created for a reasonable footprint.

* `spring-cloud-starter-bootstrap`
* `spring-cloud-starter-config`
* `spring-cloud-config-client`
* `spring-cloud-config-server`
** `spring-boot-actuator` dependency need to be added even if not used due to https://github.com/oracle/graal/issues/3345#issuecomment-847670041.
* `spring-cloud-starter-netflix-eureka-client` (Java 11 only)
** Manual configuration required, see https://github.com/oracle/graal/issues/3392 related issue.
*  `spring-cloud-starter-task`
* `spring-cloud-function-web`
** `--enable-https` flag is required for HTTPS support.
* `spring-cloud-function-adapter-aws`
* `spring-cloud-starter-function-webflux`
** `--enable-https` flag is required for HTTPS support.
* `spring-cloud-starter-sleuth`
* `spring-cloud-square` build declarative, interface-declared, proxy-powered HTTP clients with OkHTTP and Retrofit 2.

[[support-spring-data]]
=== Spring Data

[IMPORTANT]
====
https://docs.spring.io/spring-data/commons/docs/current/reference/html/#repositories.custom-implementations[Custom repository] implementation fragments need to be annotated with `@Component`.
====

==== Spring Data MongoDB

- https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongo.transactions[Multi Document Transactions] are currently not supported.

[[support-others]]
=== Others

* https://micrometer.io/[Micrometer]
* Lombok
* Spring Kafka
* Spring Session (Redis and JDBC)
* https://grpc.io/[GRPC]
* H2 database
* Mysql JDBC driver
* PostgreSQL JDBC driver
