[[support]]
== Support

=== GraalVM

GraalVM version {graalvm-version} is supported, see related https://www.graalvm.org/release-notes/[release notes].

=== Language

Java 8, Java 11 and Kotlin 1.3+ are supported.

Be aware that Java 11 native images are currently impacted by a transient footprint issue that may lead
(or not) to bigger images due to https://github.com/oracle/graal/issues/3163[oracle/graal#3163].

Kotlin Coroutines are supported but require additional reflection entries due to how Coroutines generates
bytecode with an `Object` return type, see https://github.com/spring-projects/spring-framework/issues/21546[this related issue]
for a potential future fix.

=== Spring Boot

IMPORTANT: `spring-native` {version} is designed to be used with Spring Boot {boot-version}.

The following starters are supported, the group ID is `org.springframework.boot` unless specified otherwise.

* `spring-boot-starter-actuator`: WebMvc and WebFlux are supported, as well as metrics and tracing infrastructure. Beware that actuators significantly increase the footprint, this will be optimized in a future release.
** `--enable-https` flag is required for HTTPS support.
* `spring-boot-starter-data-elasticsearch`
** `--enable-https` flag is required for HTTPS support.
* `spring-boot-starter-data-jdbc`
** `--enable-all-security-services` and `-H:+AddAllCharsets` may be required depending on your JDBC driver.
* `spring-boot-starter-data-jpa`
** You need to configure https://docs.jboss.org/hibernate/orm/5.4/topical/html_single/bytecode/BytecodeEnhancement.html#_build_time_enhancement[Hibernate build-time bytecode enhancement]
** `hibernate.bytecode.provider=none` is automatically set
** `--enable-all-security-services` and `-H:+AddAllCharsets` may be required depending on your JDBC driver.
* `spring-boot-starter-data-mongodb`
* `spring-boot-starter-data-neo4j`
** `--enable-https --enable-all-security-services` are required to use any secure bolt connection (everything bolt+s(sc) or neo4j+s(sc).
* `spring-boot-starter-data-r2dbc`
* `spring-boot-starter-data-redis`
* `spring-boot-starter-jdbc`
** `--enable-all-security-services` and `-H:+AddAllCharsets` may be required depending on your JDBC driver.
* `spring-boot-starter-logging`
* `spring-boot-starter-mail`
* `spring-boot-starter-thymeleaf`
* `spring-boot-starter-rsocket`
* `spring-boot-starter-validation`
* `spring-boot-starter-security`: WebMvc and WebFlux form login, HTTP basic authentication and OAuth 2.0 are supported. RSocket security is also supported.
** `--enable-all-security-services` flag is required.
* `spring-boot-starter-oauth2-resource-server`: WebMvc and WebFlux are supported.
** `--enable-all-security-services` flag is required.
* `spring-boot-starter-oauth2-client`: WebMvc and WebFlux are supported.
** `--enable-all-security-services` flag is required.
* `spring-boot-starter-webflux`: only Netty is supported for now.
** `--enable-https` flag is required for HTTPS support.
* `spring-boot-starter-web`:
** Only Tomcat is supported for now.
** `tomcat-embed-programmatic` dependency can be used instead of `tomcat-embed-core` and `tomcat-embed-websocket` ones for optimized footprint. If you are using `spring-boot-starter-web` and Maven, you should use the following `pom.xml` configuration:
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-core</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-websocket</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>org.apache.tomcat.experimental</groupId>
    <artifactId>tomcat-embed-programmatic</artifactId>
    <version>${tomcat.version}</version>
</dependency>
```
** `--enable-https` flag is required for HTTPS support.
* `spring-boot-starter-websocket`
* `com.wavefront:wavefront-spring-boot-starter`
** `--enable-https` flag is required.

=== Spring Cloud

IMPORTANT: `spring-native` {version} is designed to be used with Spring Cloud {cloud-version}.

Group ID is `org.springframework.cloud`.

* `spring-cloud-starter-bootstrap`
* `spring-cloud-starter-config`
* `spring-cloud-config-server`
* `spring-cloud-starter-netflix-eureka-client`
* `spring-cloud-starter-netflix-eureka-server`
* `spring-cloud-function-web`
** `--enable-https` flag is required for HTTPS support.
* `spring-cloud-function-adapter-aws`
* `spring-cloud-starter-function-webflux`
** `--enable-https` flag is required for HTTPS support.

=== Others

- Spring Kafka
- https://grpc.io/[GRPC]

=== Limitations

CGLIB proxies are not supported, only JDK dynamic proxies on interfaces are supported for now.

It is fine for applications to just use `@Configuration` without setting `proxyBeanMethods=false`
and use method parameters to inject bean dependencies, this is handled by Spring Native to not require
a CGLIB proxy.
