[[support]]
== Support

=== GraalVM

GraalVM version {graalvm-version} is supported, see related https://www.graalvm.org/release-notes/[release notes].

=== Language

Java 8, Java 11 and Kotlin 1.3+ are supported.

Be aware that Java 11 native images are currently impacted by a transient footprint issue that may lead (or not) to bigger images due to https://github.com/oracle/graal/issues/3163[oracle/graal#3163].

Kotlin Coroutines are supported but require additional reflection entries due to how Coroutines generates bytecode with an `Object` return type, see https://github.com/spring-projects/spring-framework/issues/21546[this related issue] for a potential future fix.

Some features like HTTPS may require some additional flags, check <<native-image-options>> for more details.

=== Spring Boot

IMPORTANT: `spring-native` {version} is designed to be used with Spring Boot {spring-boot-version}.

The following starters are supported, the group ID is `org.springframework.boot` unless specified otherwise.

* `spring-boot-starter-actuator`: WebMvc and WebFlux are supported, as well as metrics and tracing infrastructure.
Beware that actuators significantly increase the footprint, this will be optimized in a future release.
* `spring-boot-starter-data-elasticsearch`
* `spring-boot-starter-data-jdbc`
* `spring-boot-starter-data-jpa`
** You need to configure https://docs.jboss.org/hibernate/orm/5.4/topical/html_single/bytecode/BytecodeEnhancement.html#_build_time_enhancement[Hibernate build-time bytecode enhancement]
** `hibernate.bytecode.provider=none` is automatically set
* `spring-boot-starter-data-mongodb`
* `spring-boot-starter-data-neo4j`
* `spring-boot-starter-data-r2dbc`
* `spring-boot-starter-data-redis`
* `spring-boot-starter-jdbc`
* `spring-boot-starter-logging`
* `spring-boot-starter-mail`
* `spring-boot-starter-thymeleaf`
* `spring-boot-starter-rsocket`
* `spring-boot-starter-validation`
* `spring-boot-starter-security`: WebMvc and WebFlux form login, HTTP basic authentication and OAuth 2.0 are supported.
RSocket security is also supported.
* `spring-boot-starter-oauth2-resource-server`: WebMvc and WebFlux are supported.
* `spring-boot-starter-oauth2-client`: WebMvc and WebFlux are supported.
* `spring-boot-starter-webflux`: only Netty is supported for now.
* `spring-boot-starter-web`:
** Only Tomcat is supported for now.
** `org.apache.tomcat.experimental:tomcat-embed-programmatic` dependency can be used instead of `tomcat-embed-core` and `tomcat-embed-websocket` ones for optimized footprint. If you are using `spring-boot-starter-web` and Maven, you should use the following `pom.xml` configuration:
====
[source,xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-core</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-websocket</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>org.apache.tomcat.experimental</groupId>
    <artifactId>tomcat-embed-programmatic</artifactId>
    <version>${tomcat.version}</version>
</dependency>
----
====
** `--enable-https` flag is required for HTTPS support.
* `spring-boot-starter-websocket`
* `com.wavefront:wavefront-spring-boot-starter`
** `--enable-https` flag is required.

IMPORTANT: Devtools is not supported yet, you can follow
https://github.com/spring-projects-experimental/spring-native/issues/532[spring-native#532] to be aware when it will.

=== Spring Cloud

IMPORTANT: `spring-native` {version} is designed to be used with Spring Cloud {spring-cloud-version}.

Group ID is `org.springframework.cloud`.

* `spring-cloud-starter-bootstrap`
* `spring-cloud-starter-config`
* `spring-cloud-config-server`
* `spring-cloud-starter-netflix-eureka-client`
* `spring-cloud-starter-netflix-eureka-server`
* `spring-cloud-function-web`
** `--enable-https` flag is required for HTTPS support.
* `spring-cloud-function-adapter-aws`
* `spring-cloud-starter-function-webflux`
** `--enable-https` flag is required for HTTPS support.

=== Others

- Spring Kafka
- https://grpc.io/[GRPC]
- H2 database
- Mysql JDBC driver
- PostgreSQL JDBC driver

=== Limitations

CGLIB proxies are not supported, only JDK dynamic proxies on interfaces are supported for now.

It is fine for applications to just use `@Configuration` without setting `proxyBeanMethods=false` and use method parameters to inject bean dependencies, this is handled by Spring Native to not require a CGLIB proxy.
