[[support]]
== Support

IMPORTANT: Spring Native is now superseded by Spring Boot 3 official native support, see https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html[the related reference documentation] for more details.

This section defines the GraalVM version, languages and dependencies that have been validated against Spring Native {version},
which provides beta support on the scope defined in this section. You can try it on your projects if they are using those
supported dependencies, and https://github.com/spring-projects-experimental/spring-native/issues[raise bugs] or
https://github.com/spring-projects-experimental/spring-native/pulls[contribute pull requests] if something goes wrong.

Beta support also means that breaking changes will happen, but a migration path will be provided and documented.

[[support-graalvm]]
=== GraalVM

GraalVM version {graalvm-version} is supported, see the related https://www.graalvm.org/release-notes/[release notes].
GraalVM issues impacting the Spring ecosystem are identified on their issue tracker using https://github.com/oracle/graal/labels/spring[the `spring` label].

[[support-language]]
=== Language

Java 11, Java 17 and Kotlin 1.5+ are supported.

WARNING: Java compiler `-parameters` flag is required since the `.class` resources, used as a fallback mechanism on the JVM to retrieve parameter names, are typically not available on native. Spring Boot plugin automatically configures it on modules where it is applied, but make sure to configure it explicitly when that's not the case (typically in multi modules projects or when using Kotlin multiplatform).

[[support-tooling]]
=== Tooling

Maven and Gradle (version 7 or above) are supported.

[[support-feature-flags]]
=== Feature flags

Some features like HTTPS may require some additional flags, check <<native-image-options>> for more details.
When it recognizes certain usage scenarios, Spring Native tries to set required flags automatically.

[[support-spring-boot]]
=== Spring Boot

NOTE: Spring Native {version} has been tested against Spring Boot {spring-boot-version}.

The following starters are supported, the group ID is `org.springframework.boot` unless specified otherwise.

==== Starters requiring special build configuration

* `spring-boot-starter-web`
** Only Tomcat is supported for now.
** `--enable-https` flag is required for server HTTPS support.
** `org.apache.tomcat.experimental:tomcat-embed-programmatic` dependency should be used for optimized footprint.

[source,xml,subs="attributes,verbatim",role="primary"]
.Maven
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-core</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-websocket</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>org.apache.tomcat.experimental</groupId>
    <artifactId>tomcat-embed-programmatic</artifactId>
    <version>${tomcat.version}</version>
</dependency>
----
[source,subs="attributes,verbatim",role="secondary"]
.Gradle Groovy
----
implementation('org.springframework.boot:spring-boot-starter-web') {
    exclude group: 'org.apache.tomcat.embed', module: 'tomcat-embed-core'
    exclude group: 'org.apache.tomcat.embed', module: 'tomcat-embed-websocket'
}
implementation "org.apache.tomcat.experimental:tomcat-embed-programmatic:${dependencyManagement.importedProperties["tomcat.version"]}"
----
[source,Kotlin,subs="attributes,verbatim",role="secondary"]
.Gradle Kotlin
----
implementation("org.springframework.boot:spring-boot-starter-web") {
    exclude(group = "org.apache.tomcat.embed", module = "tomcat-embed-core")
    exclude(group = "org.apache.tomcat.embed", module = "tomcat-embed-websocket")
}
implementation("org.apache.tomcat.experimental:tomcat-embed-programmatic:${dependencyManagement.importedProperties["tomcat.version"]}")
----

* `spring-boot-starter-actuator`
** WebMvc and WebFlux are supported, as well as metrics and tracing infrastructure.
** Exclude `io.micrometer:micrometer-core` when metrics are not used for optimized footprint.

[source,xml,subs="attributes,verbatim",role="primary"]
.Maven
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-actuator</artifactId>
    <exclusions>
        <exclusion>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-core</artifactId>
        </exclusion>
    </exclusions>
</dependency>
----
[source,subs="attributes,verbatim",role="secondary"]
.Gradle Groovy
----
implementation('org.springframework.boot:spring-boot-starter-actuator') {
    exclude group: 'io.micrometer', module: 'micrometer-core'
}
----
[source,Kotlin,subs="attributes,verbatim",role="secondary"]
.Gradle Kotlin
----
implementation("org.springframework.boot:spring-boot-starter-actuator") {
    exclude(group = "io.micrometer", module = "micrometer-core")
}
----

* `spring-boot-starter-test`
** https://github.com/spring-projects-experimental/spring-native/issues/1063[Mockito is not yet supported].
** See testing support documentation in <<getting-started-native-build-tools>>.

==== Starters requiring no special build configuration

* `spring-boot-starter-amqp`
* `spring-boot-starter-aop`
** May require additional `@AotProxyHint`.
* `spring-boot-starter-batch`
** May require some additional hints, see https://github.com/spring-projects-experimental/spring-native/blob/main/samples/batch-io/src/main/java/com/example/batch/BatchApplication.java[`batch-io` sample].
** See https://github.com/spring-projects-experimental/spring-native/issues/459[related #459 issue] about supporting class that implements multiple interfaces.
* `spring-boot-starter-data-elasticsearch`
* `spring-boot-starter-data-jdbc`
* `spring-boot-starter-data-jpa`
** If you want a lighter alternative, `spring-boot-starter-data-jdbc` which provides a smaller native footprint is a great alternative.
** You need to configure https://docs.jboss.org/hibernate/orm/5.4/topical/html_single/bytecode/BytecodeEnhancement.html#_build_time_enhancement[Hibernate build-time bytecode enhancement]
** `hibernate.bytecode.provider=none` is automatically set
* `spring-boot-starter-data-mongodb`
** https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongo.transactions[Multi Document Transactions] are currently not supported.
* `spring-boot-starter-data-neo4j`
* `spring-boot-starter-data-r2dbc`
* `spring-boot-starter-data-redis`
* `spring-boot-starter-hateoas`
* `spring-boot-starter-jdbc`
* `spring-boot-starter-logging`
** Logback is supported with some limitations
*** Configuration with embedded `logback.xml` https://github.com/spring-projects-experimental/spring-native/issues/625[is not supported yet].
*** Configuration with embedded `logback-spring.xml`, via `myapp -Dlogging.config=logback-config.xml` or `myapp --logging.config=logback-config.xml` is supported but you need to enable <<aot-build-setup-configuration, XML support>> and add https://search.maven.org/artifact/org.codehaus.janino/janino[`org.codehaus.janino:janino` dependency] (see the `logger` sample).
*** http://logback.qos.ch/manual/configuration.html#conditional[Conditional processing in Logback] configuration with Janino library has limited support. Only simple expressions of `isDefined()` and `isNull()` having string literal as argument are supported.
** Log4j2 is not supported yet, see https://github.com/spring-projects-experimental/spring-native/issues/115[#115].
* `spring-boot-starter-mail`
* `spring-boot-starter-oauth2-resource-server`: WebMvc and WebFlux are supported.
* `spring-boot-starter-oauth2-client`: WebMvc and WebFlux are supported.
* `spring-boot-starter-rsocket`
* `spring-boot-starter-security`: WebMvc and WebFlux form login, HTTP basic authentication, OAuth 2.0 and LDAP are supported.
RSocket security is also supported.
* `spring-boot-starter-thymeleaf`
* `spring-boot-starter-validation`
* `spring-boot-starter-webflux`:
** Client and server are supported.
** For Web support, only Reactor Netty is supported for now.
** For WebSocket support, Tomcat, Jetty 9, Undertow and Reactor Netty are supported. Jetty 10 is not supported.
* `spring-boot-starter-websocket`
* `com.wavefront:wavefront-spring-boot-starter`
* `spring-boot-starter-quartz`
** Supports the http://www.quartz-scheduler.org/[Quartz Job Scheduling] engine.
** It adds types required by Quartz, and automatically registers any `Job` subclasses for reflection.

[[support-spring-cloud]]
=== Spring Cloud

NOTE: Spring Native {version} has been tested against Spring Cloud {spring-cloud-version}.

Group ID is `org.springframework.cloud`.

NOTE: When using Spring Native, `spring.cloud.refresh.enabled` is set to `false` for compatibility and footprint reasons. `spring.sleuth.async.enabled` is also set to `false` since this feature leads to too much proxies created for a reasonable footprint.

* `spring-cloud-starter-config`
* `spring-cloud-config-client`
* `spring-cloud-config-server`
* `spring-cloud-starter-netflix-eureka-client`
*  `spring-cloud-starter-task`
* `spring-cloud-function-web`
** `FunctionalSpringApplication` is not supported
** `--enable-https` flag is required for HTTPS support.
* `spring-cloud-function-adapter-aws`
* `spring-cloud-starter-function-webflux`
** `--enable-https` flag is required for HTTPS support.
* `spring-cloud-starter-sleuth`
* `spring-cloud-sleuth-zipkin`

NOTE: Spring Cloud Bootstrap is no longer supported.

NOTE: While building a project that contains Spring Cloud Config Client, it is necessary to make sure that the configuration data source that it connects to (such as, Spring Cloud Config Server, Consul, Zookeeper, Vault, etc.) is available. For example, if you retrieve configuration data from Spring Cloud Config Server, make sure you have its instance running and available at the port indicated in the Config Client setup. This is necessary because the application context is being optimized at build time and requires the target environment to be resolved.

[[support-others]]
=== Others

* https://micrometer.io/[Micrometer]
* Google Cloud Platform libraries via `com.google.cloud:native-image-support` dependency, see https://github.com/GoogleCloudPlatform/native-image-support-java[this repository] for more information
* Lombok
* Spring Kafka
* Spring Session (Redis and JDBC)
* https://grpc.io/[GRPC]
* H2 database
* Mysql JDBC driver
* PostgreSQL JDBC driver
* Wavefront

[[limitations]]
=== Limitations

* When using programmatic APIs like `RestTemplate` or `WebClient`, reflection-based serialization like Jackson requires additional `@TypeHint`, this limitation could be removed later via https://github.com/spring-projects-experimental/spring-native/issues/1152[#1152].
* Kotlin Coroutines are supported but currently require additional reflection entries due to how Coroutines generates bytecode with an `Object` return type.
* Sealed class are not supported yet due to https://github.com/oracle/graal/issues/3870.
* https://docs.spring.io/spring-data/commons/docs/current/reference/html/#repositories.custom-implementations[Custom repository] implementation fragments need to be annotated with `@Component`.
