[[tracing-agent]]
== Tracing agent

The GraalVM native image tracing agent allows to intercept reflection, resources or proxy usage on the JVM in order to generate the related native configuration. Spring Native should generate most of this native configuration automatically, but the tracing agent can be used to quickly identify the missing entries.

When using the agent to compute configuration for native-image, there are a couple of approaches:

* Launch the app directly and exercise it.
* Run application tests to exercise the application.

The first option is interesting for identifying the missing native configuration when a library or a pattern is not recognized by Spring Native.

NOTE: See this related https://github.com/oracle/graal/issues/3283[graal#3283] issue that should make this process much easier. For now, you can make a manual diff between the native configuration generated by Spring Native and the one generated by the tracing agent.

The second option sounds more appealing for a repeatable setup but by default the generated configuration will include anything required by the test infrastructure, which is unnecessary when the application runs for real.
To address this problem the agent supports an access-filter file that will cause certain data to be excluded from the generated output.

[[tracing-agent-testing]]
=== Testing with the agent to compute configuration

==== A basic access-filter file

This is a simple `access-filter.json` file. 


[source,json,subs="attributes,verbatim"]
----
{ "rules": [
  {"excludeClasses": "org.apache.maven.surefire.**"},
  {"excludeClasses": "net.bytebuddy.**"},
  {"excludeClasses": "org.apiguardian.**"},
  {"excludeClasses": "org.junit.**"},
  {"excludeClasses": "org.mockito.**"},
  {"excludeClasses": "org.springframework.test.**"},
  {"excludeClasses": "org.springframework.boot.test.**"},
  {"excludeClasses": "com.example.demo.test.**"}
  ]
}
----

Most of these lines would apply to any Spring application, except for the last one which is application specific and will need tweaking to match the package of a specific applications tests.

==== Using the access-filter file

The access-filter.json file is specified with the `access-filter-file` option as part of the agentlib string:

`-agentlib:native-image-agent=access-filter-file=access-filter.json,config-output-dir=target/classes/META-INF/native-image`

==== Using it with maven

Let's look at how to pull the ideas here together and apply them to a project.

Since Spring takes an eager approach when building the application context, a very basic test that starts the application context will exercise a lot of the Spring infrastructure that needs to produce native-image configuration.
This test would suffice for that and could be placed in `src/test/java`:


[source,java]
----
package com.example.demo.test;

import org.junit.jupiter.api.Test;

import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;

@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
public class AppContextStartupTest {

	@Test
	public void contextLoads() {
	}
}
----


Now take the `access-filter.json` file from above and place it in `src/test/resources` folder.

This following snippet would go into the maven pom:


[source,xml,subs="attributes,verbatim"]
----
<plugins>
    <!-- ... -->
    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
            <argLine>-DspringAot=true -agentlib:native-image-agent=access-filter-file=src/test/resources/access-filter.json,config-merge-dir=target/classes/META-INF/native-image</argLine>
        </configuration>
    </plugin>
</plugins>
----

NOTE: You need to activate the AOT mode when running the tracing agent as documented in <<spring-aot-modes>>.

Also update the `spring-aot` build plugin to enable the `native-agent` mode:

[source,xml,subs="attributes,verbatim"]
----
<plugin>
    <groupId>org.springframework.experimental</groupId>
    <artifactId>spring-aot-maven-plugin</artifactId>
    <configuration>
        <mode>native-agent</mode>
    </configuration>
</plugin>
----


That's it, build your native image, it should generate the native configuration during the tests and run with the `native-agent` mode design to just add the missing bits.
If that's not enough, you can add additional native configuration using `@NativeHint` annotations.
