[[tracing-agent]]
== Tracing agent

The GraalVM native image https://www.graalvm.org/reference-manual/native-image/Agent/[tracing agent] allows to intercept reflection, resources or proxy usage on the JVM in order to generate the related native configuration. Spring Native should generate most of this native configuration automatically, but the tracing agent can be used to quickly identify the missing entries.

When using the agent to compute configuration for native-image, there are a couple of approaches:

* Launch the app directly and exercise it.
* Run application tests to exercise the application.

The first option is interesting for identifying the missing native configuration when a library or a pattern is not recognized by Spring Native.

NOTE: See this related https://github.com/oracle/graal/issues/3283[graal#3283] issue that should make this process much easier. For now, you can make a manual diff between the native configuration generated by Spring Native and the one generated by the tracing agent.

The second option sounds more appealing for a repeatable setup but by default the generated configuration will include anything required by the test infrastructure, which is unnecessary when the application runs for real.
To address this problem the agent supports an access-filter file that will cause certain data to be excluded from the generated output.

[[tracing-agent-running]]
=== Running the application with the agent to compute configuration

It is possible to use the tracing agent to run the application in AOT mode in order to compute the native configuration:

 - Configure the AOT plugin to use the `native-agent` mode.
 - Build the Spring Boot application with the AOT plugin enabled.
 - Run the app with the tracing agent and generate the config temporarily in `src/main/resources` with for example `java -DspringAot=true -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image -jar target/myapp-0.0.1-SNAPSHOT.jar`.
 - Check if the application is now working fine on native.

[[tracing-agent-testing]]
=== Testing with the agent to compute configuration

==== A basic access-filter file

Create the following `access-filter.json` file at the root of your project.


[source,json,subs="attributes,verbatim"]
----
{ "rules": [
  {"excludeClasses": "org.apache.maven.surefire.**"},
  {"excludeClasses": "net.bytebuddy.**"},
  {"excludeClasses": "org.apiguardian.**"},
  {"excludeClasses": "org.junit.**"},
  {"excludeClasses": "org.mockito.**"},
  {"excludeClasses": "org.springframework.test.**"},
  {"excludeClasses": "org.springframework.boot.test.**"},
  {"excludeClasses": "com.example.demo.test.**"}
  ]
}
----

Most of these lines would apply to any Spring application, except for the last one which is application specific and will need tweaking to match the package of a specific applications tests.

==== Using the access-filter file

The access-filter.json file is specified with the `access-filter-file` option as part of the agentlib string:

`-agentlib:native-image-agent=access-filter-file=access-filter.json,config-output-dir=target/classes/META-INF/native-image`

==== Using it with maven

Let's look at how to pull the ideas here together and apply them to a project.

Since Spring takes an eager approach when building the application context, a very basic test that starts the application context will exercise a lot of the Spring infrastructure that needs to produce native-image configuration.
This test would suffice for that and could be placed in `src/test/java`:


[source,java]
----
package com.example.demo.test;

import org.junit.jupiter.api.Test;

import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class ApplicationTests {

	@Test
	public void contextLoads() {
	}
}
----

NOTE: Make sure to exercise all the required code path to allow the agent to generate all the required native configuration. For example, that could mean to request with an http client all the web endpoints.

This following snippet would go into the maven pom:


[source,xml,subs="attributes,verbatim"]
----
<plugins>
    <!-- ... -->
    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
            <argLine>-agentlib:native-image-agent=access-filter-file=access-filter.json,config-merge-dir=target/classes/META-INF/native-image</argLine>
        </configuration>
    </plugin>
</plugins>
----

NOTE: You need to activate the AOT mode when running the tracing agent on the application as documented in <<spring-aot-modes>>,
for tests this is not needed since AOT mode is enabled automatically when AOT files are detected.

Also update the `spring-aot` build plugin to enable the `native-agent` mode in order to not generate `*-config.json` files since the agent will take care of that:

[source,xml,subs="attributes,verbatim"]
----
<plugin>
    <groupId>org.springframework.experimental</groupId>
    <artifactId>spring-aot-maven-plugin</artifactId>
    <configuration>
        <mode>native-agent</mode>
    </configuration>
</plugin>
----

Run the JVM tests with `mvn clean test` to generate the native configuration, then build the native image with `mvn -DskipTests -Pnative package`. If that's not enough, you can add additional native configuration using `@NativeHint` annotations.

WARNING: If you see a `java.lang.ClassCastException: sun.reflect.generics.tree.FieldTypeSignature[] cannot be cast to java.lang.reflect.Type[]` error, this is a GraalVM bug related to https://github.com/oracle/graal/pull/4075. A workaround is to replace `queryAll*` entries by "All*" entries.