[[troubleshooting]]
== Troubleshooting

While trying to build native images, various things can go wrong, either at image build time or at runtime when you try to launch the built image.
Usually, the problem is a lack of native configuration, so be sure to check <<native-hints>> first thing.
Reading {graalvm-native-docs}/[Native image reference documentation] could also probably help.

This section explores some of the errors that can be encountered and possible fixes or workarounds.

Make sure to check https://github.com/oracle/graal/projects/2?card_filter_query=label%3Aspring[GraalVM native image known issues related to Spring] as well as https://github.com/spring-projects-experimental/spring-native/issues[Spring Native open issues] before creating a new one.

[[troubleshooting-native-image-failing]]
=== `native-image` is failing

The image can fail for a number of reasons.
We have described the most common causes and their solutions here.

==== DataSize was unintentionally initialized at build time

If you see an error like:


[source,bash]
----
Error: Classes that should be initialized at run time got initialized during image building:
 org.springframework.util.unit.DataSize was unintentionally initialized at build time. To see why org.springframework.util.unit.DataSize got initialized use --trace-class-initialization
----

You have probably tried to compile a Spring Boot application to native without the `spring-native` dependency and Spring AOT plugin.
See related <<getting-started-native-image>> and <<getting-started-buildpacks>> documentation.

==== WARNING: Could not register reflection metadata

Those warnings are expected for now, and should be removed in a future version, see https://github.com/spring-projects-experimental/spring-native/issues/502#issuecomment-786933142[#502] for more details.

==== Out of memory error when building the native image

Out of memory error can materialize with error messages like `Error: Image build request failed with exit status 137`.

`native-image` consumes a lot of RAM, we recommend a machine with at least 16G of RAM.

If you are using containers, on Mac, it is recommended to increase the memory allocated to Docker to at least 8G (and potentially to add more CPUs as well) since `native-image` compiler is a heavy process.
See this https://stackoverflow.com/questions/44533319/how-to-assign-more-memory-to-docker-container/44533437#44533437[Stackoverflow answer] for more details.

On Windows, make sure to enable the https://docs.docker.com/docker-for-windows/wsl/[Docker WSL 2 backend] for better performances.

==== Builder lifecycle 'creator' failed with status code 145

This is a generic error triggered by Docker and forwarded by Spring Boot Buildpacks support. `native-image` command has likely failed, so check the error messages in the output. If you can't find anything, check if that's not an out of memory error as described above.

[[troubleshooting-image-does-not-run]]
=== The built image does not run

If your built image does not run, you can try a number of fixes.
This section describes those possible fixes.

==== Missing resource bundles

In some cases, when there is a problem, the error message tries to tell you exactly what to do, as follows:


[source,bash]
----
Caused by: java.util.MissingResourceException:
  Resource bundle not found javax.servlet.http.LocalStrings.
  Register the resource bundle using the option
    -H:IncludeResourceBundles=javax.servlet.http.LocalStrings.
----


You should add resource configuration using <<native-hints>>.

==== Application failed to start when running `mvn spring-boot:run`

Because of a temporary limitation of the AOT plugin, developers need to trigger the `package` phase if they wish to run the application with the Spring Boot Maven plugin:
please use `mvn package spring-boot:run`.

[[logback-workaround]]
==== How can I configure programmatically Logback as a `logback.xml` alternative?

As a workaround for https://github.com/spring-projects-experimental/spring-native/issues/625[#625], you can create a `src/main/resources/META-INF/services/ch.qos.logback.classic.spi.Configurator` file with the following content:

[source,subs="attributes,verbatim"]
----
org.springframework.boot.logging.logback.CustomConfigurator
----

Add a `org.springframework.boot.logging.logback.CustomConfigurator` class similar to the one bellow which will disable Spring Boot logging configuration override, reuse Spring Boot defaults, and allow you to customize Logback `LoggerContext`:

[source,java,subs="attributes,verbatim"]
----
public class CustomConfigurator extends ContextAwareBase implements Configurator {

	@Override
	public void configure(LoggerContext context) {

		// Set this to avoid LoggerContext override by Spring Boot
		context.putObject(LoggingSystem.class.getName(), new Object());

		// Apply Spring Boot default configuration, make sure CustomConfigurator
		// is in the org.springframework.boot.logging.logback package
		LogbackConfigurator configurator = new LogbackConfigurator(context);
		new DefaultLogbackConfiguration(null).apply(configurator);
		context.setPackagingDataEnabled(true);

		// Your custom configuration goes there
		context.addListener(...);
	}
}
----

Add also the following hint to your Spring Boot application class:

[source,java,subs="attributes,verbatim"]
----
@InitializationHint(types = ColorConverter.class, initTime = InitializationTime.BUILD)
----

==== Missing configuration

The Spring AOT plugin will do the best it can to catch everything but it doesn't understand every bit of code out there.
In these situations you can write native configuration yourself, see <<native-hints>>, <<tracing-agent>> and <<how-to-contribute>>.

==== AotProxyHint errors

When running native image an error indicating a `AotProxyHint` is missing may be produced, like this:

----
Caused by: java.lang.IllegalStateException: Class proxy missing at runtime, hint required at build time: @AotProxyHint(targetClass=com.example.batch.ItemReaderListener.class, interfaces={org.springframework.aop.scope.ScopedObject.class, java.io.Serializable.class, org.springframework.aop.framework.AopInfrastructureBean.class})
----

This indicates a hint was missing to construct the proxy at build time. New classes cannot be generated at runtime in native images. By including these
hints on your application (alongside the other hints), the original building of your application will generate the required proxy classes (and their
support classes) and they will be included in the native-image. At runtime when a class proxy is required, these classes generated earlier will then be loaded.

The error message includes exactly the hint text that needs to be pasted into the source.

A class proxy is a proxy that extends a class. This is in contrast to a regular `JdkProxyHint` which only specifies a set of interfaces to be implemented
by a JDK Proxy class.

==== No access hint found for import selector: XXX

See <<how-to-contribute-design-import-selectors>>.

[[troubleshooting-working-with-multi-modules]]
=== Working with Multi-Modules projects

The Spring Boot and AOT plugins should only be applied to the module that contains the main application class.
We've shared https://github.com/spring-projects-experimental/spring-native/tree/main/samples/multi-modules/[a sample application showing how to set up multi-modules projects with Gradle and Maven].


[[troubleshooting-working-with-snapshots]]
=== Working with snapshots

Snapshots are regularly published and obviously ahead of releases and milestones.
If you wish to use the snapshot versions you should use the following repository:


[source,xml,subs="attributes,verbatim"]
----
<repositories>
    <!-- ... -->
    <repository>
        <id>spring-snapshots</id>
        <name>Spring Snapshots</name>
        <url>https://repo.spring.io/snapshot</url>
    </repository>
</repositories>
----

