[[troubleshooting]]
== Troubleshooting

While trying to build native images, various things can go wrong, either at image-build time or at runtime when you try to launch the built image.
Usually, the problem is a lack of native configuration, so be sure to check <<native-hints>> first thing.
Reading {graalvm-native-docs}/[Native image reference documentation] could also probably help.

This section explores some of the errors that can be encountered and possible fixes or workarounds.

Make sure to check https://github.com/oracle/graal/projects/2?card_filter_query=label%3Aspring[GraalVM native image known issues related to Spring] as well as https://github.com/spring-projects-experimental/spring-native/issues[Spring Native open issues] before creating a new one.

=== `native-image` is failing

The image can fail for a number of reasons.
We have described the most common causes and their solutions here.

==== DataSize was unintentionally initialized at build time

If you see an error like:

====
[source,bash]
----
Error: Classes that should be initialized at run time got initialized during image building:
 org.springframework.util.unit.DataSize was unintentionally initialized at build time. To see why org.springframework.util.unit.DataSize got initialized use -H:+TraceClassInitialization
----
====

You have probably tried to compile a Spring Boot application to native without the `spring-native` dependency and Spring AOT plugin.
See related <<getting-started-native-image>> and <<getting-started-buildpacks>> documentation.

==== Out of memory error when building the native image

`native-image` consumes a lot of RAM, we recommend a machine with at least 16G of RAM.

If you are using containers, on Mac, it is recommended to increase the memory allocated to Docker to at least 8G (and potentially to add more CPUs as well) since `native-image` compiler is a heavy process.
See this https://stackoverflow.com/questions/44533319/how-to-assign-more-memory-to-docker-container/44533437#44533437[Stackoverflow answer] for more details.

On Windows, make sure to enable the https://docs.docker.com/docker-for-windows/wsl/[Docker WSL 2 backend] for better performances.

=== The built image does not run

If your built image does not run, you can try a number of fixes.
This section describes those possible fixes.

==== Missing resource bundles

In some cases, when there is a problem, the error message tries to tell you exactly what to do, as follows:

====
[source,bash]
----
Caused by: java.util.MissingResourceException:
  Resource bundle not found javax.servlet.http.LocalStrings.
  Register the resource bundle using the option
    -H:IncludeResourceBundles=javax.servlet.http.LocalStrings.
----
====

You should add resource configuration using <<native-hints>>.

==== Missing configuration

The Spring AOT plugin will do the best it can to catch everything but it doesn't understand every bit of code out there.
In these situations you can write native configuration yourself, see <<native-hints>> and <<how-to-contribute>>.

===== Run with the agent

Now simply run the application, with the following addition to the Java command to collect configuration in that folder:

`-agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image`

When the next native-image run happens it should automatically additionally include this collected configuration.

==== No access hint found for import selector: XXX

Spring Native chases down configuration references to other configurations (`@Import` usages).
However if you use an import selector, that means code is deciding what the next imported configuration should be, which is harder to follow.
Spring Native does not do that level of analysis (it could get very complicated).
This means that, although the feature can tell it has encountered a selector, it does not know what types that selector needs reflective access to or what further configurations it references.
Now, Spring Native could simply continue and maybe it would work, maybe it would crash at runtime.
Typically, the error produced when things go wrong due to this missing information is very cryptic.
If the selector is doing a "`if this type is around, return this configuration to include`", it may be not finding some type (when it is really there but is not exposed in the image) and not including some critical configuration.
For this reason, Spring Native analysis fails early and fast, indicating that it does not know what a particular selector is doing.
To fix it, take a look in the selector in question and craft a quick hint for it.
See {github-commits}/1251a274f81a3087b456d2178d2ae6405676d23b[this commit] that was fixing this kind of problem for a Spring Security ({github-issues}/60[issue]).

you can temporarily turn this hard error into a warning since it is possible that, in your case, you do not need what the selector is doing.
To do so, specify the `failOnMissingSelectorHint` option to `false` to cause log messages about the problem but not a hard fail.
Note that using warnings rather than errors can cause serious problems for your application.

=== Working with snapshots

Snapshots are regularly published and obviously ahead of releases and milestones.
If you wish to use the snapshot versions you should use the following repository:

====
[source,xml,subs="attributes,verbatim"]
----
<repositories>
    <!-- ... -->
    <repository>
        <id>spring-snapshots</id>
        <name>Spring Snapshots</name>
        <url>https://repo.spring.io/snapshot</url>
    </repository>
</repositories>
----
====
