ARG BASE_IMAGE
FROM harbor-repo.vmware.com/dockerhub-proxy-cache/library/$BASE_IMAGE

ARG MAVEN_VERSION=3.6.3

ENV PATH="/opt:/opt/apache-maven-$MAVEN_VERSION/bin:$PATH"
ENV SPRING_PROFILES_ACTIVE=ci

RUN apt-get -y update \
 && apt-get -y install git jq curl python unzip bc bsdmainutils mongodb-server redis-server mysql-client mysql-server build-essential gdb daemon sudo \
 && mkdir -p /var/run/mysqld \
 && mkdir -p /var/log/mysql \
 && echo "mysqld_safe --skip-grant-tables &" > /tmp/mysql.sh \
 && echo "mysqladmin --silent --wait=30 ping || exit 1" >> /tmp/mysql.sh \
 && echo "mysql -e 'CREATE DATABASE IF NOT EXISTS petclinic;'" >> /tmp/mysql.sh \
 && echo "mysql -e 'ALTER DATABASE petclinic DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'" >> /tmp/mysql.sh \
 && chmod +x /tmp/mysql.sh \
 && cd /opt \
 && curl -LO https://repo1.maven.org/maven2/org/apache/maven/apache-maven/$MAVEN_VERSION/apache-maven-$MAVEN_VERSION-bin.zip \
 && unzip apache-maven-${MAVEN_VERSION}-bin.zip \
 && rm apache-maven-${MAVEN_VERSION}-bin.zip \
 && curl -L https://github.com/fullstorydev/grpcurl/releases/download/v1.5.0/grpcurl_1.5.0_linux_x86_64.tar.gz | tar -xz \
 && rm LICENSE \
 && curl -sL https://deb.nodesource.com/setup_12.x | bash - \
 && apt-get -y install nodejs \
 && curl -LO https://github.com/tecfu/tty-table/archive/master.zip \
 && unzip master.zip \
 && rm master.zip \
 && cd tty-table-master \
 && npm i -g \
 && cd .. \
 && rm -rf tty-table-master \
	 && curl -LO https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.9.3-amd64.deb \
 && dpkg -i elasticsearch-7.9.3-amd64.deb \
 && rm elasticsearch-7.9.3-amd64.deb \
 && echo "JAVA=\"\$ES_HOME/jdk/bin/java\"" | tee -a /usr/share/elasticsearch/bin/elasticsearch-env \
 && echo "JAVA_TYPE=\"bundled jdk\"" | tee -a /usr/share/elasticsearch/bin/elasticsearch-env \
 && chmod 770 /var/lib/elasticsearch \
 && chmod 770 /var/log/elasticsearch \
 && curl -LO https://dist.neo4j.org/deb/neo4j_3.5.21_all.deb \
 && dpkg --force-all -i neo4j_3.5.21_all.deb \
 && rm neo4j_3.5.21_all.deb \
 && echo "dbms.security.auth_enabled=false" | tee -a  /etc/neo4j/neo4j.conf \
 && npm cache clean --force \
 && rm -rf /var/cache/apt/archives \
 && rm -rf /var/lib/apt/lists/*

CMD mkdir /tmp/data && /usr/bin/mongod --fork --dbpath /tmp/data --logpath /tmp/data/mongod.log && redis-server --daemonize yes && /tmp/mysql.sh && /usr/share/elasticsearch/bin/elasticsearch -d && neo4j start && native-image --version && /bin/bash
