ARG BASE_IMAGE
FROM $BASE_IMAGE

ARG USER
ARG USER_ID
ARG USER_GID

RUN (groupadd --gid "${USER_GID}" "${USER}" || echo "No groupadd needed") && \
    useradd \
      --uid ${USER_ID} \
      --gid ${USER_GID} \
      --create-home \
      --shell /bin/bash \
      ${USER} && \
      chown -R ${USER_ID}:${USER_GID} /var/lib/mysql && \
      chown -R ${USER_ID}:${USER_GID} /var/log/mysql && \
      chown -R ${USER_ID}:${USER_GID} /var/run/mysqld && \
      chown -R ${USER_ID}:${USER_GID} /var/log/elasticsearch && \
      chown -R ${USER_ID}:${USER_GID} /var/lib/neo4j && \
      chown -R ${USER_ID}:${USER_GID} /var/log/neo4j && \
      chown -R ${USER_ID}:${USER_GID} /var/run/neo4j
