ARG BASE_IMAGE
FROM $BASE_IMAGE

ARG MAVEN_VERSION=3.6.3

ENV PATH="/opt:/opt/apache-maven-$MAVEN_VERSION/bin:$PATH"
ENV SPRING_PROFILES_ACTIVE=ci

RUN apt-get -y update \
 && apt-get -y install git curl python unzip bc bsdmainutils mongodb-server redis-server mysql-client mysql-server build-essential gdb \
 && mkdir -p /var/run/mysqld \
 && mkdir -p /var/log/mysql \
 && echo "mysqld_safe --skip-grant-tables &" > /tmp/mysql.sh \
 && echo "mysqladmin --silent --wait=30 ping || exit 1" >> /tmp/mysql.sh \
 && echo "mysql -e 'CREATE DATABASE IF NOT EXISTS petclinic;'" >> /tmp/mysql.sh \
 && echo "mysql -e 'ALTER DATABASE petclinic DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'" >> /tmp/mysql.sh \
 && chmod +x /tmp/mysql.sh \
 && cd /opt \
 && curl -LO https://repo1.maven.org/maven2/org/apache/maven/apache-maven/$MAVEN_VERSION/apache-maven-$MAVEN_VERSION-bin.zip \
 && unzip apache-maven-${MAVEN_VERSION}-bin.zip \
 && rm apache-maven-${MAVEN_VERSION}-bin.zip \
 && curl -L https://github.com/fullstorydev/grpcurl/releases/download/v1.5.0/grpcurl_1.5.0_linux_x86_64.tar.gz | tar -xz \
 && rm LICENSE \
 && curl -sL https://deb.nodesource.com/setup_12.x | bash - \
 && apt-get -y install nodejs \
 && curl -LO https://github.com/tecfu/tty-table/archive/master.zip \
 && unzip master.zip \
 && rm master.zip \
 && cd tty-table-master \
 && npm i -g \
 && cd .. \
 && rm -rf tty-table-master \
 && npm cache clean --force \
 && rm -rf /var/cache/apt/archives \
 && rm -rf /var/lib/apt/lists/*


CMD mkdir /tmp/data && /usr/bin/mongod --fork --dbpath /tmp/data --logpath /tmp/data/mongod.log && redis-server --daemonize yes && /tmp/mysql.sh && native-image --version && /bin/bash
