github-repo: "https://github.com/spring-projects-experimental/spring-native.git"
github-repo-name: "spring-projects-experimental/spring-native"
docker-hub-organization: "springci"
artifactory-server: "https://repo.spring.io"
branch: "0.11.x"
milestone: "0.11.x"
build-name: "spring-native"
concourse-url: "https://ci.spring.io"
task-timeout: 30m

graalvm-repo: "https://github.com/oracle/graal.git"
graalvm-stable-branch: "release/graal-vm/21.2"
graalvm-dev-branch: "release/graal-vm/21.3"
jvmci-stable-java11: "https://github.com/graalvm/labs-openjdk-11/releases/download/jvmci-21.2-b08/labsjdk-ce-11.0.12+6-jvmci-21.2-b08-linux-amd64.tar.gz"
jvmci-dev-java11: "https://github.com/graalvm/labs-openjdk-11/releases/download/jvmci-21.3-b03/labsjdk-ce-11.0.12+5-jvmci-21.3-b03-linux-amd64.tar.gz"
