github-repo: "https://github.com/spring-projects-experimental/spring-native.git"
github-repo-name: "spring-projects-experimental/spring-native"
docker-hub-organization: "springci"
artifactory-server: "https://repo.spring.io"
branch: "main"
milestone: "0.9.x"
build-name: "spring-native"
concourse-url: "https://ci.spring.io"
task-timeout: 30m

graalvm-repo: "https://github.com/oracle/graal.git"
graalvm-stable-branch: "release/graal-vm/21.0"
graalvm-dev-branch: "main"
jvmci-stable-java11: "https://github.com/graalvm/labs-openjdk-11/releases/download/jvmci-21.0-b06/labsjdk-ce-11.0.10+8-jvmci-21.0-b06-linux-amd64.tar.gz"
jvmci-dev-java11: "https://github.com/graalvm/labs-openjdk-11/releases/download/jvmci-21.1-b02/labsjdk-ce-11.0.11+5-jvmci-21.1-b02-linux-amd64.tar.gz"
