anchors:
  artifactory-repo-put-params: &artifactory-repo-put-params
    repo: libs-snapshot-local
    folder: distribution-repository
    build_uri: "https://ci.spring.io/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
    build_number: "${BUILD_PIPELINE_NAME}-${BUILD_JOB_NAME}-${BUILD_NAME}"
    disable_checksum_uploads: true
    exclude:
      - "**/*.effective-pom"
      - "*/spring-native-docs-*.jar"
  artifactory-task-params: &artifactory-task-params
    ARTIFACTORY_SERVER: ((artifactory-server))
    ARTIFACTORY_USERNAME: ((artifactory-username))
    ARTIFACTORY_PASSWORD: ((artifactory-password))
  docker-hub-task-params: &docker-hub-task-params
    DOCKER_HUB_USERNAME: ((docker-hub-username))
    DOCKER_HUB_PASSWORD: ((docker-hub-password))
  git-repo-resource-source: &git-repo-resource-source
    uri: ((github-repo))
    username: ((github-username))
    password: ((github-password))
    branch: ((branch))
  registry-image-resource-source: &registry-image-resource-source
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: ((milestone))
  slack-fail-params: &slack-fail-params
    text: >
      :concourse-failed: <https://ci.spring.io/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}|${BUILD_PIPELINE_NAME} ${BUILD_JOB_NAME} failed!>
    silent: true
    icon_emoji: ":concourse:"
    username: concourse-ci
resource_types:
  - name: artifactory-resource
    type: registry-image
    source:
      repository: springio/artifactory-resource
      tag: 0.0.14
  - name: pull-request
    type: registry-image
    source:
      repository: teliaoss/github-pr-resource
      tag: v0.23.0
  - name: slack-notification
    type: registry-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest
resources:
  - name: git-repo
    type: git
    icon: github
    source:
      <<: *git-repo-resource-source
  - name: ci-images-git-repo
    type: git
    icon: github
    source:
      <<: *git-repo-resource-source
      paths: ["ci/images/*"]
  - name: git-pull-request
    type: pull-request
    icon: source-pull
    source:
      access_token: ((github-ci-pull-request-token))
      repository: ((github-repo-name))
      base_branch: ((branch))
      ignore_paths: ["ci/*"]
  - name: graalvm-stable-git-repo
    type: git
    icon: github
    source:
      uri: ((graalvm-repo))
      branch: ((graalvm-stable-branch))
  - name: graalvm-dev-git-repo
    type: git
    icon: github
    source:
      uri: ((graalvm-repo))
      branch: ((graalvm-dev-branch))
  - name: ci-image
    type: registry-image
    icon: docker
    source:
      <<: *registry-image-resource-source
      repository: ((docker-hub-organization))/spring-native-ci
  - name: graalvm-ce-stable-java11-image
    type: registry-image
    icon: docker
    source:
      <<: *registry-image-resource-source
      repository: ((docker-hub-organization))/graalvm-ce
      tag: stable-java11-((milestone))
  - name: graalvm-ce-dev-java11-image
    type: registry-image
    icon: docker
    source:
      <<: *registry-image-resource-source
      repository: ((docker-hub-organization))/graalvm-ce
      tag: dev-java11-((milestone))
  - name: spring-native-stable-java11-image
    type: registry-image
    icon: docker
    source:
      <<: *registry-image-resource-source
      repository: ((docker-hub-organization))/spring-native
      tag: stable-java11-((milestone))
  - name: spring-native-dev-java11-image
    type: registry-image
    icon: docker
    source:
      <<: *registry-image-resource-source
      repository: ((docker-hub-organization))/spring-native
      tag: dev-java11-((milestone))
  - name: artifactory-repo
    type: artifactory-resource
    icon: package-variant
    source:
      uri: ((artifactory-server))
      username: ((artifactory-username))
      password: ((artifactory-password))
      build_name: ((build-name))
  - name: github-release
    type: github-release
    icon: briefcase-download
    source:
      owner: spring-projects-experimental
      repository: spring-native
      access_token: ((github-ci-release-token))
      pre_release: false
  - name: every-day
    type: time
    source: {interval: 24h}
jobs:
  - name: build-ci-image
    plan:
      - get: git-repo
      - get: ci-images-git-repo
        trigger: true
      - task: build-ci-image
        privileged: true
        file: git-repo/ci/tasks/build-ci-image.yml
        output_mapping:
          image: ci-image
        vars:
          ci-image-name: ci-image
      - put: ci-image
        params:
          image: ci-image/image.tar
  - name: check-graalvm-ce-stable-change
    plan:
      - get: graalvm-stable-git-repo
        trigger: true
  - name: check-graalvm-ce-stable-every-day
    plan:
      - get: graalvm-stable-git-repo
        passed: [check-graalvm-ce-stable-change]
      - get: every-day
        trigger: true
  - name: build-graalvm-ce-stable-image
    plan:
      - get: git-repo
      - get: ci-images-git-repo
      - get: graalvm-stable-git-repo
        passed: [check-graalvm-ce-stable-every-day]
        trigger: true
      - get: every-day
        passed: [check-graalvm-ce-stable-every-day]
      - task: build-graalvm-ce-stable-image
        privileged: true
        file: git-repo/ci/tasks/build-graalvm-ce-image.yml
        output_mapping:
          image: graalvm-ce-stable-java11-image
        vars:
          ci-image-name: graalvm-ce-image
          jvmci-url: ((jvmci-stable-java11))
          graalvm-branch: ((graalvm-stable-branch))
      - put: graalvm-ce-stable-java11-image
        params:
          image: graalvm-ce-stable-java11-image/image.tar
  - name: check-graalvm-ce-dev-change
    plan:
      - get: graalvm-dev-git-repo
        trigger: true
  - name: check-graalvm-ce-dev-every-day
    plan:
      - get: graalvm-dev-git-repo
        passed: [check-graalvm-ce-dev-change]
      - get: every-day
        trigger: true
  - name: build-graalvm-ce-dev-image
    plan:
      - get: git-repo
      - get: ci-images-git-repo
      - get: graalvm-dev-git-repo
        passed: [check-graalvm-ce-dev-every-day]
        trigger: true
      - get: every-day
        passed: [check-graalvm-ce-dev-every-day]
      - task: build-graalvm-ce-dev-image
        privileged: true
        file: git-repo/ci/tasks/build-graalvm-ce-image.yml
        output_mapping:
          image: graalvm-ce-dev-java11-image
        vars:
          ci-image-name: graalvm-ce-image
          jvmci-url: ((jvmci-dev-java11))
          graalvm-branch: ((graalvm-dev-branch))
      - put: graalvm-ce-dev-java11-image
        params:
          image: graalvm-ce-dev-java11-image/image.tar
  - name: build-spring-native-stable-image
    plan:
      - get: git-repo
      - get: ci-images-git-repo
      - get: every-day
        passed: [build-graalvm-ce-stable-image]
        trigger: true
      - task: build-spring-native-stable-image
        privileged: true
        file: git-repo/ci/tasks/build-spring-native-image.yml
        output_mapping:
          image: spring-native-stable-java11-image
        vars:
          ci-image-name: spring-native-image
          base-image: "((docker-hub-organization))/graalvm-ce:stable-java11-((milestone))"
      - put: spring-native-stable-java11-image
        params:
          image: spring-native-stable-java11-image/image.tar
  - name: build-spring-native-dev-image
    plan:
      - get: git-repo
      - get: ci-images-git-repo
      - get: every-day
        passed: [build-graalvm-ce-dev-image]
        trigger: true
      - task: build-spring-native-dev-image
        privileged: true
        file: git-repo/ci/tasks/build-spring-native-image.yml
        output_mapping:
          image: spring-native-dev-java11-image
        vars:
          ci-image-name: spring-native-image
          base-image: "((docker-hub-organization))/graalvm-ce:dev-java11-((milestone))"
      - put: spring-native-dev-java11-image
        params:
          image: spring-native-dev-java11-image/image.tar
  - name: build-key-samples-java11
    public: true
    serial: true
    plan:
      - get: spring-native-stable-java11-image
      - get: git-repo
        trigger: true
      - task: build
        privileged: true
        image: spring-native-stable-java11-image
        file: git-repo/ci/tasks/build-key-samples.yml
        params:
          <<: *docker-hub-task-params
  - name: build-samples-stable-java11
    public: true
    plan:
      - get: spring-native-stable-java11-image
      - get: git-repo
      - get: every-day
        trigger: true
      - do:
        - task: build
          privileged: true
          image: spring-native-stable-java11-image
          file: git-repo/ci/tasks/build-samples.yml
          params:
            <<: *docker-hub-task-params
  - name: build-samples-dev-java11
    public: true
    plan:
      - get: spring-native-dev-java11-image
      - get: git-repo
      - get: every-day
        trigger: true
      - task: build
        privileged: true
        image: spring-native-dev-java11-image
        file: git-repo/ci/tasks/build-samples.yml
        params:
          <<: *docker-hub-task-params
  - name: deploy
    public: true
    plan:
      - get: ci-image
      - get: git-repo
        passed:
          - build-key-samples-java11
        trigger: true
      - task: build-project
        image: ci-image
        privileged: true
        timeout: ((task-timeout))
        file: git-repo/ci/tasks/build-project.yml
      - put: artifactory-repo
        params:
          <<: *artifactory-repo-put-params
  - name: build-pull-requests
    serial: true
    public: true
    plan:
      - get: spring-native-stable-java11-image
      - get: git-repo
        resource: git-pull-request
        trigger: true
        version: every
      - do:
        - put: git-pull-request
          params:
            path: git-repo
            status: pending
        - task: build-project
          privileged: true
          image: spring-native-stable-java11-image
          file: git-repo/ci/tasks/build-pr-project.yml
          params:
            <<: *docker-hub-task-params
        on_success:
          put: git-pull-request
          params:
            path: git-repo
            status: success
        on_failure:
          put: git-pull-request
          params:
            path: git-repo
            status: failure
  - name: stage-release
    serial: true
    plan:
      - get: ci-image
      - get: git-repo
        trigger: false
      - task: stage
        image: ci-image
        file: git-repo/ci/tasks/stage.yml
        params:
          RELEASE_TYPE: RELEASE
      - put: artifactory-repo
        params:
          <<: *artifactory-repo-put-params
          repo: libs-staging-local
      - put: git-repo
        params:
          repository: stage-git-repo
  - name: promote-release
    serial: true
    plan:
      - get: ci-image
      - get: git-repo
        trigger: false
      - get: artifactory-repo
        trigger: false
        passed: [ stage-release ]
        params:
          download_artifacts: true
          save_build_info: true
      - task: promote
        image: ci-image
        file: git-repo/ci/tasks/promote.yml
        params:
          RELEASE_TYPE: RELEASE
          <<: *artifactory-task-params
  - name: create-github-release
    serial: true
    plan:
      - get: ci-image
      - get: git-repo
      - get: artifactory-repo
        trigger: true
        passed: [ promote-release ]
        params:
          download_artifacts: false
          save_build_info: true
      - task: generate-changelog
        file: git-repo/ci/tasks/generate-changelog.yml
        params:
          RELEASE_TYPE: RELEASE
          GITHUB_USERNAME: ((github-username))
          GITHUB_TOKEN: ((github-ci-release-token))
      - put: github-release
        params:
          name: generated-changelog/tag
          tag: generated-changelog/tag
          body: generated-changelog/changelog.md
groups:
  - name: "builds"
    jobs: ["build-key-samples-java11", "deploy", "build-samples-stable-java11", "build-samples-dev-java11"]
  - name: "releases"
    jobs: ["stage-release", "promote-release", "create-github-release"]
  - name: "ci-images"
    jobs: ["build-ci-image", "check-graalvm-ce-stable-change", "check-graalvm-ce-stable-every-day", "build-graalvm-ce-stable-image", "check-graalvm-ce-dev-change", "check-graalvm-ce-dev-every-day", "build-graalvm-ce-dev-image", "build-spring-native-stable-image", "build-spring-native-dev-image" ]
  - name: "pull-requests"
    jobs: [ "build-pull-requests" ]
