package org.springframework.nativex.buildtools;

import org.springframework.core.Ordered;

/**
 * A callback for contributing sources and resources to the Bootstrap source set.
 * Contributors get access to the application runtime classpath, but do not see artifacts
 * generated by other contributors.
 *
 * <p>Invoked with an {@link Ordered order} of {@code 0} by default, considering overriding {@link #getOrder()}
 * to customize this behaviour.
 * 
 * @author Brian Clozel
 */
@FunctionalInterface
public interface BootstrapContributor extends Ordered {

	/**
	 * Contribute additional sources and resources to the Bootstrap source set.
	 * @param context the current build context
	 */
	void contribute(BuildContext context);

	@Override
	default int getOrder() {
		return 0;
	}

}