[[agent]]
=== Using the GraalVM agent

The feature is a work in progress, it doesn't understand all of Spring yet, but perhaps more importantly it doesn't understand what else your app might be doing with various other non-Spring related dependencies.
In situations like this it can be useful to try the agent which may catch 'other things' your application is doing.
You can attach the GraalVM agent to an application and, during the course of the application's execution, it produce the necessary configuration files for a subsequent `native-image` build.
As the application runs, it observes the types being reflectively accessed, the resources being loaded, and the proxies being requested, and it captures this information in `.json` files.

This section walks through using the agent to compute the configuration data and then build a `native-image` using it.
A real application is used to show the process, but the same techniques should apply to any application.

NOTE: Currently, there are agent bugs, and we cover those, including how they manifest and how to do deal with them, as we go.

==== Download and install GraalVM

From GraalVM builds:

- Install GraalVM {graal-version} Java 8 distribution from https://github.com/graalvm/graalvm-ce-builds/releases[here]
- Set `JAVA_HOME` and `PATH` appropriately for that GraalVM version.
- Run `gu install native-image` to bring in the native-image extensions to the JDK.

Or you can use https://sdkman.io/[SDKMAN] to easily switch between GraalVM versions:

- https://sdkman.io/install[Install SDKMAN]
- Install GraalVM with `sdk install java {graal-version}.r8-grl`
- Run `gu install native-image` to bring in the native-image extensions to the JDK.

==== Setup the sample project

Like the instructions for using the feature, here we use the getting started REST service guide.
This is the sample project we trace with the agent and then build into a `native-image`.
The following commands install the REST service:

====
[source,bash]
----
git clone https://github.com/spring-guides/gs-rest-service
cd gs-rest-service/complete
----
====

===== Update the `pom.xml` file

IMPORTANT: Ensure that the project uses a supported version of Spring Boot.

Upgrade the project to Spring Boot {boot-version}:

====
[source,xml,subs="attributes,verbatim"]
----
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>{boot-version}</version>
    <relativePath/> <!-- lookup parent from repository -->
</parent>
----
====

===== Add the Maven plugin

GraalVM provides a https://www.graalvm.org/docs/reference-manual/native-image/#integration-with-maven[Maven plugin] that we are going to bring in here. Paste the following XML into the `pom.xml` file (we use it later to invoke the native image build):

====
[source,xml,subs="attributes,verbatim"]
----
<profiles>
  <profile>
    <id>graal</id>
    <build>
      <plugins>
        <plugin>
          <groupId>org.graalvm.nativeimage</groupId>
          <artifactId>native-image-maven-plugin</artifactId>
          <version>{graal-version}</version>
          <configuration>
            <buildArgs>-Dspring.native.mode=agent --no-fallback -H:+ReportExceptionStackTraces --no-server</buildArgs>
          </configuration>
          <executions>
            <execution>
              <goals>
                <goal>native-image</goal>
              </goals>
              <phase>package</phase>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-maven-plugin</artifactId>
        </plugin>
      </plugins>
    </build>
  </profile>
</profiles>
----
====

The important part is the `<buildArgs>..</buildArgs>` block that shows the options we pass to the `native-image` operation and the `spring-graalvm-native` feature.
Those prefixed `-D` are aimed at the feature.

NOTE: Notice the `--no-server` option.
Like a Gradle daemon, the server here is supposed to help accelerate subsequent builds.
Unfortunately, there is an https://github.com/oracle/graal/issues/1952[issue] where the server causes different results to come out of the compilation.
In particular, we have seen logging disappear the server is used to aid compilation.
Hence, using the server to aid compilation is turned off here.

===== Add the repository for `spring-graalvm-native`

If necessary, add the repository for the `spring-graalvm-native` dependency, as follows:

====
[source,xml,subs="attributes,verbatim"]
----
<repositories>
	<!-- ... -->

	<repository>
		<id>spring-{repository}</id>
		<name>Spring {repository}</name>
		<url>https://repo.spring.io/{repository}</url>
	</repository>
</repositories>
----
====

===== Add the feature and appropriate configuration dependencies

The following listing adds the needed dependencies:

====
[source,xml,subs="attributes,verbatim"]
----
<dependencies>
    <!-- ... -->

    <dependency>
        <groupId>org.springframework.experimental</groupId>
        <artifactId>spring-graalvm-native</artifactId>
        <version>{version}</version>
    </dependency>

    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context-indexer</artifactId>
    </dependency>
</dependencies>
----
====

* Why do we need `spring-graalvm-native`?
This is discussed in more detail later in this section.
Basically, the feature is being used in a lightweight mode here where it is not providing all the configuration.
Rather, it provides only the initialization configuration.
That is because the agent does not compute this information.

* The `spring-context-indexer` has been in Spring for a while.
In a `native-image`, all notion of classpath is lost, so it is not possible to explore the classpath to find components at runtime.
The indexer actually produces a list of components at Java compile time and captures it in a `spring.components` file in the built application.
If Spring starts and finds this file, it uses it instead of attempting to explore the classpath.
The indexer can be used for this whether building a native image or running your application as a standard Java application.

===== Set `the start-class` element

The native image build needs to know the entry point to your application. It does consult a few places to find it.
However, in our sample we should set it in the `properties section` of the `pom.xml` file, as follows:

====
[source,xml]
----
<properties>
    <!-- ... -->
    <start-class>com.example.restservice.RestServiceApplication</start-class>
</properties>
----
====

===== Update the source code

In the case of this sample, no changes need to be made.
However, in some Boot applications, you may need to make some tweaks to ensure they are not doing anything that is not supported by GraalVM native images.

====== Proxies

The only kind of proxy allowed with native images is a JDK proxy.
It is not possible to use CGLIB or some other kind of generated proxy.
Boot 2.2 added the option to avoid creating these kinds of `native-image` incompatible proxies for configuration class contents, and this happens to suit `native-image` compilation.
The enhancement in question is discussed https://github.com/spring-projects/spring-framework/wiki/What%27s-New-in-Spring-Framework-5.x#core-container[here].
Basically, applications need to switch to using `proxyBeanMethods=false` in their configuration annotations.
The framework code has already all moved to this model.

Adapt `RestServiceApplication.java` accordingly:

====
[source,java]
----
@SpringBootApplication(proxyBeanMethods = false)
public class RestServiceApplication {

    public static void main(String[] args) {
        SpringApplication.run(RestServiceApplication.class, args);
    }

}
----
====

==== Create a location for the generated configuration

This can be anywhere, but that location needs to be under a location of `META-INF/native-image` and on the classpath so that the native image operation automatically picks it up.
If we want to keep this configuration around, we can generate it straight into the project (and perhaps store it in version control), as follows:

====
[source,bash]
----
mkdir -p src/main/resources/META-INF/native-image
----
====

NOTE: The "`proper`" location is perhaps a `<groupid>/<artifactid>` location below native-image, but we keep it simple here for now.

==== Run the application with the agent

The following commands run the application with the agent:

====
[source,bash]
----
mvn clean package
java -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image \
  -Dorg.graalvm.nativeimage.imagecode=agent \
  -jar target/rest-service-0.0.1-SNAPSHOT.jar
----
====

It runs as normal.

IMPORTANT: While it is up to you to make sure you exercise any codepaths, you want to ensure they are covered by the native image that will be built, exercising those paths may cause extra reflection access or resource loading and in other situations. Here, go to the `http://localhost:8080/greeting` endpoint, otherwise some codepaths could be missed.

ALSO-IMPORTANT: Notice the setting of `org.graalvm.nativeimage.imagecode`. Some behaviours in the framework code
may be different if it recognizes it is in a native image (perhaps working around features not supported in
native-images). Ideally those are the codepaths we want to exercise when running with the agent, hence
setting it when attaching the agent. There is a GraalVM https://github.com/oracle/graal/issues/2395[issue open]
to cover having the agent do this by default.

Shutdown the app with CTRL + C for example.

Notice the files that now exist in the folder:

====
[source,bash]
----
ls -l src/main/resources/META-INF/native-image
total 256
-rw-r--r--  1 foo  bar      4 18 Mar 18:59 jni-config.json
-rw-r--r--  1 foo  bar   1057 18 Mar 18:59 proxy-config.json
-rw-r--r--  1 foo  bar  98309 18 Mar 18:59 reflect-config.json
-rw-r--r--  1 foo  bar  17830 18 Mar 18:59 resource-config.json
----
====

==== What about initialization configuration?

The agent does not compute which types need build-time versus run-time initialization.
For this reason, the `spring-graalvm-native` feature is still going to be used, but only to provide that initialization information.
All the reflection, resource, and proxy configuration is going to be what we generated.

NOTE: The feature is also providing a couple of substitutions.
These are kind of "`patches`" for classes in the framework or dependent libraries that do not properly support `native-image`.
These should be temporary, and the proper solution should be pushed back into the framework or library concerned.
You might have to develop substitutions of your own if your dependent libraries are slow to fix themselves for GraalVM `native-image` interoperation.

==== Build the application

The following command builds the application:

====
[source,bash]
----
mvn -Pgraal clean package
----
====

Did it build cleanly?
If so, the resultant executable is in the target folder named after the start-class (in this case, `com.example.restservice.restserviceapplication`).

Did it fail? See the <<troubleshooting>> section. As of this writing, this step works.

===== Run the application

Run the following executable to run the application:

====
[source,bash]
----
./target/com.example.restservice.restserviceapplication
----
====

It failed.
This is a realistic situation right now.
You have to work a little harder while the agent is missing things.
We do that now to troubleshoot this problem.

You should get the following exceptions when you launch it:

====
[source,bash]
----
Caused by: java.util.MissingResourceException:
Resource bundle not found javax.servlet.http.LocalStrings.
Register the resource bundle using the option
  -H:IncludeResourceBundles=javax.servlet.http.LocalStrings.
----
====

You can tweak the `pom.xml` file to add `-H:IncludeResourceBundles=javax.servlet.http.LocalStrings` to the `<buildArgs>` section as another option.

Recompile.

Now it might launch.
However, on curling to the endpoint (`curl http://localhost:8080/greeting`) it shows the following error:

====
[source,bash]
----
Caused by: java.util.MissingResourceException:
  Resource bundle not found javax.servlet.LocalStrings.
  Register the resource bundle using the option
    -H:IncludeResourceBundles=javax.servlet.LocalStrings
----
====

You can add that `-H:IncludeResourceBundles=javax.servlet.LocalStrings` to `pom.xml` `<buildArgs>` and recompile again.

Run the executable, curl to the endpoint (`curl http://localhost:8080/greeting`), it shows the following error:

====
[source,bash]
----
Caused by: java.lang.ClassNotFoundException:
  org.apache.catalina.authenticator.jaspic.AuthConfigFactoryImpl
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60) ~[na:na]
----
====

This is what happens when the agent misses a reflective usage.
This particular one is https://github.com/oracle/graal/issues/2198[issue 2198].
It has been fixed but after GraalVM 20.0.0.
In this situation, we can manually add this entry.
To do so, open `src/main/resources/META-INF/native-image/reflect-config.json` and insert the following on line 2 (after the `[` on line 1):

====
[source,json]
----
{
 "name":"org.apache.catalina.authenticator.jaspic.AuthConfigFactoryImpl",
 "allDeclaredConstructors":true,
 "allDeclaredMethods":true
},
----
====

It should now work after a rebuild. The startup time is <100ms, compared to ~1500ms when starting the fat jar.

==== Summary

Hopefully ,that has given you a taste of the process of building native images.
There is much more coming to optimize Spring in all areas: smaller images, reduced memory usage, faster native image compilation, and more.
We are also working with the GraalVM team in all the pitfall areas described earlier.
Things across the board should only get better.
If you apply these techniques to your own application and have problems, see the <<troubleshooting>> section.
