:toc: left
:toclevels: 4
:numbered:
:icons: font
:hide-uri-scheme:
:project-home: https://github.com/spring-projects-experimental/spring-graalvm-native
:version: 0.8.3-SNAPSHOT
:repository: milestone
:boot-version: 2.4.0
:graalvm-version: 20.2.0
= Spring GraalVM Native {version} reference guide
Andy Clement; Sébastien Deleuze; Filip Hanik; Dave Syer; Esteban Ginez; Jay Bryant

[[introduction]]
This guide walks you through the various options for building Spring Boot native applications using https://www.graalvm.org/reference-manual/native-image/[GraalVM native].

This involves compiling your application as normal and then running an extra native-image step that builds a self-contained platform-specific executable for that application.
The executable should have a more predictable memory profile as well as fast startup.

The key complexity in building a native image is that the image building process needs to be informed about what your application is going to do at runtime.
The build process attempts to construct the most optimal image possible and therefore tries to exclude anything not strictly required.
However, it sometimes needs a few hints so that it can ensure it includes in the image all the necessary code and data to satisfy the application runtime needs.

In particular, the following concerns apply:

* If the application is going to reflect at runtime on some type, field, method or constructor, the native image must include the data to satisfy those reflection requests.

* If the application is going to load resources (such as `application.properties`), they must be included in the image.

* If the application is going to try to use proxies at runtime, these must be generated up front during the image-build process and included in the image.

* There can be a benefit to initializing classes when the image is built, as opposed to when the resultant executable starts up.
The image build process needs to be told which classes to initialize at build time versus at run time.

There are two primary ways to communicate this information to the build process:

- Through JSON files on the classpath.
- Through a https://www.graalvm.org/sdk/javadoc/org/graalvm/nativeimage/hosted/Feature.html[GraalVM feature] that participates in the image-build process and, after analyzing the application being compiled, calls APIs to register information about reflection, resources, proxies, and so on.

It is worth mentioning that there are limitations on what GraalVM supports with respect to native images.
If your application is doing any of these, it may not be possible to build a native image.
The limitations are discussed https://github.com/oracle/graal/blob/master/substratevm/Limitations.md[here].

== Spring GraalVM Native

The `spring-graalvm-native` project is incubating support for building Spring Boot native applications using GraalVM native.
It is mainly composed of:

- `spring-graalvm-native-feature`: this module is a https://www.graalvm.org/sdk/javadoc/org/graalvm/nativeimage/hosted/Feature.html[GraalVM feature]. It is a kind of plugin for the native-image compilation process (which creates the native-image from the built class files). The feature participates in the compilation lifecycle, being invoked at different compilation stages to offer extra information about the application to aid in the image construction.
- `spring-graalvm-native-configuration`: this module contains configuration hints for Spring classes, including various Spring Boot auto-configurations.
- `spring-graalvm-native-substitutions`: this module allows patching (temporarily) some parts of Spring Boot and Spring Framework to improve the compatibility and efficiency of Spring native images.
- `spring-graalvm-native`: this module aggregates the feature, configuration and substitutions ones to generate the artifact to consume.
- `spring-graalvm-native-samples`: contains various samples that demonstrate the feature usage and are used as integration tests.
- `spring-graalvm-native-docs`: contains the asciidoc documentation sources.
- `spring-graalvm-native-tools`: tools used for reviewing image building configuration and output.

It supports the following modes using `-Dspring.native.mode=<mode>` on the `native-image` command line:

- `reflection` (activated by default) provides resource, initialization, proxy and reflection (using auto-configuration hints) configuration for native images as well as substitutions.
- `init` (manually activated) should be used if only wishing to provide initialization configuration and substitutions.
- `agent` (experimental, activated when agent-generated config is present) is using the configuration generated by the tracing agent as a basis and also provides additional hints for components like controllers, etc.
- `functional` (experimental, activated automatically when https://github.com/spring-projects-experimental/spring-fu[spring-fu] or https://github.com/spring-projects-experimental/spring-init/[spring-init] are in the classpath) is designed to work with functional bean registration. In this mode the feature will provide initialization, resource configuration, substitutions and `spring.factories` functional alternative (only Spring Boot `spring.factories` are supported for now).


== Getting Started

There are two main ways to build Spring Boot native application:

- Using <<getting-started-buildpacks, Spring Boot Maven or Gradle Buildpacks support>> to generate a lightweight container containing a native executable
- Using <<getting-started-native-image, GraalVM native image Maven plugin support>> to generate a native executable

include::getting-started-buildpacks.adoc[]

include::getting-started-native-image.adoc[]

include::samples.adoc[]

include::support.adoc[]

include::options.adoc[]

include::agent.adoc[]

include::troubleshooting.adoc[]

include::how-to-contribute.adoc[]

== Contact us

Finally, before you post about it not working, please check the <<troubleshooting,troubleshooting guide>>, which is full of information on pitfalls, common problems, and how to deal with them (through fixes and workarounds).

We would love to hear about your successes and failures through the project issue tracker.
If you want to make a contribution here, see the <<how-to-contribute,how to contribute guide>>.
Please be aware this project is still incubating and, as such, some of these options and extension APIs are still evolving and may change before it is finally considered done.
