:toc: left
:toclevels: 4
:numbered:
:icons: font
:hide-uri-scheme:
:project-home: https://github.com/spring-projects-experimental/spring-graalvm-native
:version: 0.7.0.BUILD-SNAPSHOT
:repository: snapshot
:boot-version: 2.3.0.RELEASE
:graal-version: 20.1.0
= Spring GraalVM Native {version} reference guide
Andy Clement; Sébastien Deleuze; Filip Hanik; Dave Syer; Esteban Ginez; Jay Bryant

[[introduction]]
This guide walks you through the various options for building GraalVM native images for your Spring Boot applications.

This involves compiling your application as normal and then running an extra native-image step that builds a self-contained platform-specific executable for that application.
The executable should have a more predictable memory profile as well as fast startup.

The key complexity in building a native image is that the image building process needs to be informed about what your application is going to do at runtime.
The build process attempts to construct the most optimal image possible and therefore tries to exclude anything not strictly required.
However, it sometimes needs a few hints so that it can ensure it includes in the image all the necessary code and data to satisfy the application runtime needs.

In particular, the following concerns apply:

* If the application is going to reflect at runtime on some type, field, method or constructor, the native image must include the data to satisfy those reflection requests.

* If the application is going to load resources (such as `application.properties`), they must be included in the image.

* If the application is going to try to use proxies at runtime, these must be generated up front during the image-build process and included in the image.

* There can be a benefit to initializing classes when the image is built, as opposed to when the resultant executable starts up.
The image build process needs to be told which classes to initialize at build time versus at run time.

There are two primary ways to communicate this information to the build process:

* Through JSON files on the classpath.

* Through a GraalVM feature that participates in the image-build process and, after analyzing the application being compiled, calls APIs to register information about reflection, resources, proxies, and so on.

Some projects are starting to include the necessary JSON files in their default distributions (for example, Netty).

Crafting these JSON files can be tricky, but they can actually be computed by using an agent that comes with GraalVM.
Run the application and exercise all relevant code paths (possibly through tests) with the agent attached, and it produces most of the configuration.
The only part it does not compute is the initialization hints.

It is worth mentioning that there are limitations on what GraalVM supports with respect to native images.
If your application is doing any of these, it may not be possible to build a native image.
The limitations are discussed https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md[here].

== What about Spring?

The `spring-graalvm-native` project represents a work-in-progress attempt to implement a GraalVM feature.
This feature examines the Spring Boot application being built and tells the image-build process about it.
The feature understands how Spring is implemented and, so, from examining what auto-configuration is defined on the classpath (which components are defined and so on), it knows what to grant reflective access to and what to generate proxies for.

The feature is a work in progress: There are numerous sample projects for which it works, as can be seen in the samples folder within the project (<<samples,you can read more about the samples here>>), but does that mean it will work on the first thing you try it on?
That is not guaranteed.
When things do not work, do not panic, there are multiple ways to proceed, and this reference guide covers those.

See the <<feature,feature guide>> for more information on getting started with the Spring feature, including a full walkthrough with an example.

It is also possible to use the GraalVM supplied agent to determine the configuration data for your Spring application.
See <<agent,the agent guide>> for that approach.
Be aware that there are still bugs in the agent, though, and it can "`miss things`".
Resolving these misses can be tricky.
We are working with the GraalVM team to ensure issues are fixed.

There is even a hybrid model where the feature and the agent are used together.
Neither the feature nor the agent are perfect, but sometimes they can nicely complement each other's deficiencies.
See <<hybrid,the hybrid guide>>.

include::samples.adoc[]

== Guides

include::feature.adoc[]

include::agent.adoc[]

include::hybrid_feature_agent.adoc[]

include::options.adoc[]

include::troubleshooting.adoc[]

include::extension_guide.adoc[]

== Contact us

Finally, before you post about it not working, please check the <<troubleshooting,troubleshooting guide>>, which is full of information on pitfalls, common problems, and how to deal with them (through fixes and workarounds).

We would love to hear about your successes and failures through the project issue tracker.
Work has been started on an extension model that makes it easy to support areas of Spring the feature does not yet reach.
If you want to make a contribution here, see the <<extension_guide,extension guide>>.
Please be aware this is pre-1.0 and, as such, some of these options and extension APIs are still evolving and may change before it is finally considered done.
