:toc: left
:toclevels: 4
:numbered:
:icons: font
:hide-uri-scheme:
:project-home: https://github.com/spring-projects-experimental/spring-graalvm-native
:version: 0.8.3-SNAPSHOT
:repository: milestone
:boot-version: 2.4.0
:graalvm-version: 20.3.0
= Spring Native for GraalVM documentation
Version {version} - Andy Clement; Sébastien Deleuze; Filip Hanik; Dave Syer; Esteban Ginez; Jay Bryant

== Overview

Spring Native for https://www.graalvm.org[GraalVM] provides support for compiling Spring to native executables using
https://www.graalvm.org/reference-manual/native-image/[native-image] compiler.

Compared to the Java Virtual Machine, GraalVM native offers advantages like the following, enabling cheaper and more
sustainable hosting for certain kinds of workloads (microservices, functions) well suited for containers and https://kubernetes.io/[Kubernetes]:

- Instant startup
- Instant peek performance
- Reduced memory consumption

But also a few drawbacks that could be reduced in the future as GraalVM native evolves:

- Slower and heavy build
- Less runtime optimizations after warmup
- Less mature than the JVM with some different behaviors

The key differences between the regular JVM and this GraalVM native platform are:

- A static analysis of your application from the main entry point is performed at build time.
- The unused parts are removed at build time.
- Configuration is required for reflection, resources, and dynamic proxies.
- Classpath fixed at build time.
- No class lazy loading: everything shipped in the executables will be loaded in memory at startup.
- Some code will run at build time!
- There are some https://github.com/oracle/graal/blob/master/substratevm/Limitations.md[limitations].

The goal of this project is to incubate the support for Spring Native, an alternative to Spring JVM, in order to provide
a native deployment option designed to be packaged in lightweight containers. In practice, the target is
to support your Spring application (typically Spring Boot ones), unmodified, on this new platform.
Beware that we are not here yet, see the <<support>> documentation for more details.

=== Modules

The Spring Native for GraalVM project is composed of the following modules:

- `spring-graalvm-native`: this module aggregates the feature, configuration and substitutions ones to generate the artifact to consume.
- `spring-graalvm-native-feature`: this module is a https://www.graalvm.org/sdk/javadoc/org/graalvm/nativeimage/hosted/Feature.html[GraalVM feature]. It is a kind of plugin for the native-image compilation process (which creates the native-image from the built class files). The feature participates in the compilation lifecycle, being invoked at different compilation stages to offer extra information about the application to aid in the image construction.
- `spring-graalvm-native-configuration`: this module contains configuration hints for Spring classes, including various Spring Boot auto-configurations.
- `spring-graalvm-native-substitutions`: this module allows patching (temporarily) some parts of Spring Boot and Spring Framework to improve the compatibility and efficiency of Spring native images.
- `spring-graalvm-native-samples`: contains various samples that demonstrate the feature usage and are used as integration tests.
- `spring-graalvm-native-docs`: contains the asciidoc documentation sources.
- `spring-graalvm-native-tools`: tools used for reviewing image building configuration and output.

=== Modes

It supports the following modes using `-Dspring.native.mode=<mode>` on the `native-image` command line:

- `reflection` (activated by default) provides resource, initialization, proxy and reflection (using auto-configuration hints) configuration for native images as well as substitutions.
- `init` (manually activated) should be used if only wishing to provide initialization configuration and substitutions.
- `agent` (experimental, activated when agent-generated config is present) is using the configuration generated by the tracing agent as a basis and also provides additional hints for components like controllers, etc.
- `functional` (experimental, activated automatically when https://github.com/spring-projects-experimental/spring-fu[spring-fu] or https://github.com/spring-projects-experimental/spring-init/[spring-init] are in the classpath) is designed to work with functional bean registration. In this mode the feature will provide initialization, resource configuration, substitutions and `spring.factories` functional alternative (only Spring Boot `spring.factories` are supported for now).

include::support.adoc[]

== Getting Started

There are two main ways to build Spring Boot native application:

- Using <<getting-started-buildpacks, Spring Boot Maven or Gradle Buildpacks support>> to generate a lightweight container containing a native executable
- Using <<getting-started-native-image, GraalVM native image Maven plugin support>> to generate a native executable

include::getting-started-buildpacks.adoc[]

include::getting-started-native-image.adoc[]

include::samples.adoc[]

include::options.adoc[]

include::agent.adoc[]

include::troubleshooting.adoc[]

include::how-to-contribute.adoc[]

== Contact us

We would love to hear about your successes and failures (with minimal repro projects) through the https://github.com/spring-projects-experimental/spring-graalvm-native/issues[project issue tracker].
Before raising an issue, please check the <<troubleshooting,troubleshooting guide>>, which is full of information on pitfalls, common problems, and how to deal with them (through fixes and workarounds).

If you want to make a contribution here, see the <<how-to-contribute,how to contribute guide>>.
Please be aware this project is still incubating and, as such, some of these options and extension APIs are still evolving and may change before it is finally considered done.
