[[options]]
== Options

You can tweak the behavior of GraalVM native by setting options.
These are passed to `native-image` as command line parameters, in a `META-INF/native-image/native-image.properties` file with an `Arg` key or through the `<buildArgs>..</buildArgs>` block when invoking with Maven.

=== GraalVM options

GraalVM offers options that are enabled by default and others that are not enabled by default (some of which are recommended, though).

==== Options enabled by default

These options are enabled by default when using `spring-graalvm-native`, since they are mandatory to make a Spring application work when compiled as GraalVM native images.

* `--allow-incomplete-classpath` allows image building with an incomplete class path and reports type resolution errors at run time when they are accessed the first time, instead of during image building.

* `--report-unsupported-elements-at-runtime` reports usage of unsupported methods and fields at run time when they are accessed the first time, instead of as an error during image building.

==== Options recommended by default

* `--no-server` means do not use the image-build server which can be sometimes unreliable, see https://github.com/oracle/graal/issues/1952[graal#1952] for more details.

* `--verbose` makes image building output more verbose.

* `--no-fallback` enforces native image only runtime and disable fallback on regular JVM

* `-H:+ReportExceptionStackTraces` provides more detail should something go wrong.

==== Other options

* `--initialize-at-build-time` initializes classes by default at build time without any class or package being specified.
This option is currently (hopefully, temporarily) required for Netty-based applications but is not recommended for other applications, since it can trigger compatibility issues, especially regarding logging and static fields.
See {project-home}/issues/8[this issue] for more details.
You can use it with specific classes or package specified if needed.

* `-H:+PrintAnalysisCallTree` helps to find what classes, methods, and fields are used and why.
You can find more details in GraalVM https://github.com/oracle/graal/blob/master/substratevm/REPORTS.md[reports documentation].

* `-H:+TraceClassInitialization` provides useful information to debug class initialization issues.

=== Feature options

The current feature options are as follows:

* `-Dspring.native.remove-unused-autoconfig=true` removes unused configurations, enabling faster compilation and smaller executables.

* `-Dspring.native.mode=agent|feature|functional|hybrid` switches how much configuration the feature actually provides
to native-image.  The default is `feature` where it provides everything (including deep analysis of auto-configuration).
`agent` should be used if only wishing the feature to provide substitutions and initialization configuration - in this
mode you should have used the agent to collect the rest of the configuration.
`functional` is when working with functional bean registration (Spring Fu style). In this mode the feature
will provide initialization and resource configuration but nothing more.
Finally, `hybrid` mode is where the agent is being used to provide a bulk of the configuration but the feature will
provide initialization configuration and substitutions with a little more for resources, proxies, reflection based on
a simpler analysis of the application - it does not do deep analysis of auto configuration as the agent will have caught that.
This final mode is for when you've exercised some of your application with the agent but perhaps not everything - it may
catch those other places you missed.

* `-Dspring.native.verbose=true` outputs lots of information about the feature behavior as it processes auto-configuration and chooses which to include.

* `-Dspring.native.remove-yaml-support=true` removes Yaml support from Spring Boot, enabling faster compilation and smaller executables.

* `-Dspring.native.remove-xml-support=true` removes XML support from Spring Boot, enabling faster compilation and smaller executables.

* `-Dspring.native.remove-spel-support=true` removes SpEL support from Spring Boot, enabling faster compilation and smaller executables.

* `-Dspring.native.remove-jmx-support=true` removes JMX support from Spring Boot, enabling faster compilation and smaller executables.

* `-Dspring.native.dump-config=/tmp/dump.txt` dumps the configuration to the specified file.

* `-Dspring.native.verify=true` switches on the verifier mode.
See the <<troubleshooting>> section for more details on this experimental option.

* `-Dspring.native.missing-selector-hints=warning` switches the feature from a hard error for missing hints to a warning.
See the <<troubleshooting>> section for more details on this.

=== Optional options

* `--enable-all-security-services` required for HTTPS and crypto.

* `--static` builds a statically linked executable, useful to deploy on a `FROM scratch` Docker image.

=== Unsupported options

* `--initialize-at-build-time` without class or package specified is not supported since Spring GraalVM native support is designed to work with runtime class initialization by default (a selected set of classes are enabled at buildtime).

