[[samples]]
== Samples

There are numerous samples in the {project-home}/tree/master/spring-graalvm-native-samples[`spring-graalvm-native-samples`] subfolder of the root project.
These show the feature in use with different technologies.

The samples do not all currently use Maven. Instead, they are built for us to play around with a little more easily.
Each includes a `build.sh` script which (Java) builds the app, calls the `compile.sh` script to run the `native-image` process, and runs a `verify.sh` script to check whether the built image works.

Our build process for the feature currently runs `./build.sh` in the root of the project and then `./build-samples.sh` to build all the samples and verify everything is working.
Running `native-image` instances takes a long time and eats RAM.

The samples show the wide variety of tech that is working fine: Tomcat, Netty, Thymeleaf, JPA, and others.
The pet clinic sample brings multiple technologies together in one application.

{project-home}/tree/master/spring-graalvm-native-samples/jafu[`jafu`] and {project-home}/tree/master/spring-graalvm-native-samples/jafu-webmvc[`jafu-webmvc`] samples are based on the https://github.com/spring-projects-experimental/spring-fu[Spring Fu experimental project] and are designed to demonstrate how leveraging Spring infrastructure in a functional way ends up to smaller native images that consume less memory.

If you are starting to build your first Spring Boot application, we recommend you follow one of the guides.
