[[support]]
== Support

=== GraalVM

GraalVM version {graalvm-version} is supported.

=== Language

Java 8, Java 11 and Kotlin 1.3+ are supported.

=== Spring Boot

IMPORTANT: `spring-graalvm-native` {version} is designed to be used with Spring Boot {boot-version}.

The following starters are supported, the group ID is `org.springframework.boot` unless specified otherwise.

- `spring-boot-starter-actuator`: WebMvc and WebFlux are supported, as well as metrics and tracing infrastructure. Beware that actuators significantly increase the footprint, this will be optimized in a future release.
- `spring-boot-starter-cache`
- `spring-boot-starter-data-jdbc`
- `spring-boot-starter-data-jpa`
- `spring-boot-starter-data-mongodb`
- `spring-boot-starter-data-neo4j`
- `spring-boot-starter-data-r2dbc`
- `spring-boot-starter-data-redis`
- `spring-boot-starter-data-elasticsearch` with `org.springframework.data:spring-data-elasticsearch:4.1.0-RC1` set explicitly
- `spring-boot-starter-jdbc`
- `spring-boot-starter-logging`
- `spring-boot-starter-thymeleaf`
- `spring-boot-starter-validation`
- `spring-boot-starter-webflux`: only Netty is supported for now.
- `spring-boot-starter-web`: only Tomcat is supported for now. A lightweight version of Tomcat is available via the `org.apache.tomcat.experimental:tomcat-embed-programmatic` dependency.
- `com.wavefront:wavefront-spring-boot-starter`

=== Spring Cloud

Group ID is `org.springframework.cloud`.

- `spring-cloud-function-web`
- `spring-cloud-function-adapter-aws`
- `spring-cloud-starter-function-webflux`

=== Others

- `org.springframework.fu:spring-fu-jafu`: https://github.com/spring-projects-experimental/spring-fu/tree/master/jafu[JaFu DSL] from https://github.com/spring-projects-experimental/spring-fu[Spring Fu]
- `org.springframework.fu:spring-fu-kofu`: https://github.com/spring-projects-experimental/spring-fu/tree/master/kofu[KoFu DSL] from https://github.com/spring-projects-experimental/spring-fu[Spring Fu]
- https://grpc.io/[GRPC]

=== Limitations

In native applications, `@Bean` annotated methods do not support cross `@Bean` invocations since they require a CGLIB proxy created at runtime.
This is similar to the behavior you get with the so called https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-java-basic-concepts[lite mode] or with https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Configuration.html#proxyBeanMethods--[`@Configuration(proxyBeanMethods=false)`].
It is fine for applications to just use `@Configuration` without setting `proxyBeanMethods=false` and use method parameters to inject bean dependencies.
Libraries are encouraged to use `@Configuration(proxyBeanMethods=false)` (most of Spring portfolio currently uses this variant) since it is generally a good idea to avoid CGLIB proxies if not needed and to provide native compatibility.
This behavior could potentially become the default in a future Spring Framework version.

Only proxies on interfaces are supported for now.