[[support]]
== Support

=== GraalVM

GraalVM version {graalvm-version} is supported, see related https://www.graalvm.org/release-notes/[release notes].

=== Language

Java 8, Java 11 and Kotlin 1.3+ are supported.

=== Spring Boot

IMPORTANT: `spring-graalvm-native` {version} is designed to be used with Spring Boot {boot-version}.

The following starters are supported, the group ID is `org.springframework.boot` unless specified otherwise.

* `spring-boot-starter-actuator`: WebMvc and WebFlux are supported, as well as metrics and tracing infrastructure. Beware that actuators significantly increase the footprint, this will be optimized in a future release.
** `--enable-https` flag is required for HTTPS support.
* `spring-boot-starter-cache`
* `spring-boot-starter-data-elasticsearch`
** `--enable-https` flag is required for HTTPS support.
* `spring-boot-starter-data-jdbc`
** `--enable-all-security-services` and `-H:+AddAllCharsets` may be required depending on your JDBC driver.
* `spring-boot-starter-data-jpa`
** You need to configure https://docs.jboss.org/hibernate/orm/5.4/topical/html_single/bytecode/BytecodeEnhancement.html#_build_time_enhancement[Hibernate build-time bytecode enhancement] (https://github.com/spring-projects-experimental/spring-graalvm-native/blob/f4a9128bd7fb64f6901f84325862f58ac7dcac50/spring-graalvm-native-samples/jpa/pom.xml#L106-L126[Maven example])
** `src/main/resources/hibernate.properties` should define `hibernate.bytecode.provider=none` (https://github.com/spring-projects-experimental/spring-graalvm-native/blob/f4a9128bd7fb64f6901f84325862f58ac7dcac50/spring-graalvm-native-samples/jpa/src/main/resources/hibernate.properties[example])
** `--enable-all-security-services` and `-H:+AddAllCharsets` may be required depending on your JDBC driver.
* `spring-boot-starter-data-mongodb`
* `spring-boot-starter-data-neo4j`
* `spring-boot-starter-data-r2dbc`
* `spring-boot-starter-data-redis`
* `spring-boot-starter-jdbc`
** `--enable-all-security-services` and `-H:+AddAllCharsets` may be required depending on your JDBC driver.
* `spring-boot-starter-logging`
* `spring-boot-starter-thymeleaf`
* `spring-boot-starter-rsocket`
* `spring-boot-starter-validation`
* `spring-boot-starter-webflux`: only Netty is supported for now.
** `--enable-https` flag is required for HTTPS support.
* `spring-boot-starter-web`:
** Only Tomcat is supported for now.
** `tomcat-embed-programmatic` dependency can be used instead of `tomcat-embed-core` and `tomcat-embed-websocket` ones for optimized footprint. If you are using `spring-boot-starter-web` and Maven, you should use the following `pom.xml` configuration:
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-core</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-websocket</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>org.apache.tomcat.experimental</groupId>
    <artifactId>tomcat-embed-programmatic</artifactId>
    <version>${tomcat.version}</version>
</dependency>
```
** `--enable-https` flag is required for HTTPS support.
* `spring-boot-starter-websocket`
* `com.wavefront:wavefront-spring-boot-starter`
** `--enable-https` flag is required.

=== Spring Cloud

Group ID is `org.springframework.cloud`.

* `spring-cloud-function-web`
** `--enable-https` flag is required for HTTPS support.
* `spring-cloud-function-adapter-aws`
* `spring-cloud-starter-function-webflux`
** `--enable-https` flag is required for HTTPS support.

=== Others

- `org.springframework.fu:spring-fu-jafu`: https://github.com/spring-projects-experimental/spring-fu/tree/master/jafu[JaFu DSL] from https://github.com/spring-projects-experimental/spring-fu[Spring Fu]
- `org.springframework.fu:spring-fu-kofu`: https://github.com/spring-projects-experimental/spring-fu/tree/master/kofu[KoFu DSL] from https://github.com/spring-projects-experimental/spring-fu[Spring Fu]
- https://grpc.io/[GRPC]

=== Limitations

In native applications, `@Bean` annotated methods do not support cross `@Bean` invocations since they require a CGLIB proxy created at runtime.
This is similar to the behavior you get with the so called https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-java-basic-concepts[lite mode] or with https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Configuration.html#proxyBeanMethods--[`@Configuration(proxyBeanMethods=false)`].
It is fine for applications to just use `@Configuration` without setting `proxyBeanMethods=false` and use method parameters to inject bean dependencies.
Libraries are encouraged to use `@Configuration(proxyBeanMethods=false)` (most of Spring portfolio currently uses this variant) since it is generally a good idea to avoid CGLIB proxies if not needed and to provide native compatibility.
This behavior could potentially become the default in a future Spring Framework version.

Only proxies on interfaces are supported for now.
